/**
 * Schema del formulario de Vigilancia Epidemiológica - Brote Sarampión 2026
 * Basado en: BASE DATOS VIGILANCIA BROTE SARAMPION 2026 (IGSS)
 *
 * Cada campo mapea directamente a una columna del Google Sheet.
 * Las páginas corresponden a las secciones del Excel original.
 */

export const formTitle = 'Vigilancia Epidemiológica - Brote de Sarampión 2026'
export const formSubtitle = 'Departamento de Medicina Preventiva — Sección de Epidemiología'
export const institutionName = 'Instituto Guatemalteco de Seguridad Social'

export const pageLabels = {
  1: 'Datos Administrativos',
  2: 'Datos del Paciente',
  3: 'Embarazo',
  4: 'Consulta y Sintomatología',
  5: 'Vacunación',
  6: 'Complicaciones y Hospitalización',
  7: 'Laboratorio',
  8: 'Contactos y Clasificación',
}

export const unidadesMedicas = [
  'HOSPITAL GENERAL DE ENFERMEDADES',
  'HOSPITAL JUAN JOSE AREVALO BERMEJO',
  'HOSPITAL DE GINECO-OBSTETRICIA',
  'HOSPITAL DE REHABILITACIÓN',
  'HOSPITAL DE ACCIDENTES',
  'HOSPITAL DE ESCUINTLA',
  'HOSPITAL DE PUERTO BARRIOS',
  'HOSPITAL DE COATEPEQUE',
  'HOSPITAL DE HUEHUETENANGO',
  'HOSPITAL DE RETALHULEU',
  'HOSPITAL GENERAL DE QUETZALTENANGO',
  'HOSPITAL TIQUISATE',
  'CONSULTORIO DE ANTIGUA GUATEMALA',
  'CONSULTORIO DE GUAZACAPAN/SANTA ROSA',
  'CONSULTORIO DE JUTIAPA',
  'CONSULTORIO DE JALAPA',
  'CONSULTORIO SOLOLÁ Y SALA ANEXA HOSPITAL NACIONAL',
  'CONSULTORIO VILLA NUEVA',
  'CONSULTORIO LA GOMERA/ESCUINTLA',
  'POLICLINICA',
  'UNIDAD PERIFÉRICA ZONA CINCO',
  'CAMIP 3 ZUNIL',
  'OTRA',
]

export const departamentosGuatemala = [
  'ALTA VERAPAZ',
  'BAJA VERAPAZ',
  'CHIMALTENANGO',
  'CHIQUIMULA',
  'EL PROGRESO',
  'ESCUINTLA',
  'GUATEMALA',
  'HUEHUETENANGO',
  'IZABAL',
  'JALAPA',
  'JUTIAPA',
  'PETÉN',
  'QUETZALTENANGO',
  'QUICHÉ',
  'RETALHULEU',
  'SACATEPÉQUEZ',
  'SAN MARCOS',
  'SANTA ROSA',
  'SOLOLÁ',
  'SUCHITEPÉQUEZ',
  'TOTONICAPÁN',
  'ZACAPA',
]

export const formFields = [
  // ═══════════════════════════════════════════════════
  // PÁGINA 1: DATOS ADMINISTRATIVOS
  // ═══════════════════════════════════════════════════
  {
    id: 'diagnostico_registrado',
    label: 'Diagnóstico Registrado',
    type: 'select',
    page: 1,
    required: true,
    options: [
      'SOSPECHOSO DE SARAMPIÓN',
      'SARAMPIÓN',
      'EXANTEMA A ESTUDIO',
      'ERUPCIÓN CUTÁNEA',
      'CONTACTO ASINTOMÁTICO',
      'FIEBRE DE ORIGEN DESCONOCIDO',
      'DERMATITIS ATÓPICA',
      'ESCARLATINA',
      'RINOFARINGITIS AGUDA',
      'INFECCIÓN VIRAL NO ESPECIFICADA',
      'OTRO',
    ],
    helpText: 'Seleccione el diagnóstico registrado en la consulta',
    colSpan: 'half',
  },
  {
    id: 'diagnostico_otro',
    label: 'Especifique otro diagnóstico',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Escriba el diagnóstico',
    conditional: { dependsOn: 'diagnostico_registrado', showWhen: 'OTRO' },
    colSpan: 'half',
  },
  {
    id: 'codigo_cie10',
    label: 'Código CIE-10',
    type: 'text',
    page: 1,
    required: false,
    placeholder: 'Ej: B05, B059, R21',
    helpText: 'Código de clasificación internacional de enfermedades',
    colSpan: 'half',
    validation: { maxLength: 10 },
  },
  {
    id: 'unidad_medica',
    label: 'Unidad Médica',
    type: 'select',
    page: 1,
    required: true,
    options: unidadesMedicas,
    helpText: 'Unidad médica del IGSS que reporta',
    colSpan: 'half',
  },
  {
    id: 'unidad_medica_otra',
    label: 'Especifique la unidad médica',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Nombre de la unidad médica',
    conditional: { dependsOn: 'unidad_medica', showWhen: 'OTRA' },
    colSpan: 'half',
  },
  {
    id: 'fecha_registro_diagnostico',
    label: 'Fecha de Registro de Diagnóstico',
    type: 'date',
    page: 1,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fecha_notificacion',
    label: 'Fecha de Notificación',
    type: 'date',
    page: 1,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'semana_epidemiologica',
    label: 'Semana Epidemiológica',
    type: 'number',
    page: 1,
    required: true,
    placeholder: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 1, max: 53 },
    autoCalculate: 'epiWeek',
    dependsOnDate: 'fecha_notificacion',
    helpText: 'Se calcula automáticamente según la fecha de notificación (sistema MMWR/CDC)',
    readOnly: true,
  },
  {
    id: 'servicio_reporta',
    label: 'Servicio que Reporta',
    type: 'select',
    page: 1,
    required: true,
    options: [
      'EMERGENCIA',
      'CONSULTA EXTERNA',
      'COEX',
      'ENCAMAMIENTO',
      'OTRO',
    ],
    colSpan: 'half',
  },
  {
    id: 'envio_ficha',
    label: '¿Enviaron Ficha Epidemiológica?',
    type: 'radio',
    page: 1,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 2: DATOS GENERALES DEL PACIENTE
  // ═══════════════════════════════════════════════════
  {
    id: 'afiliacion',
    label: 'Número de Afiliación',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Número de afiliación del paciente',
    helpText: 'Número de afiliación IGSS (13 dígitos) o número de registro',
    colSpan: 'half',
    validation: { minLength: 5, maxLength: 20 },
  },
  {
    id: 'nombre_apellido',
    label: 'Nombre y Apellido',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Nombre completo del paciente',
    colSpan: 'full',
    validation: { minLength: 3, maxLength: 150 },
  },
  {
    id: 'edad_anios',
    label: 'Edad en Años',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    colSpan: 'half',
    validation: { min: 0, max: 120 },
  },
  {
    id: 'edad_meses',
    label: 'Edad en Meses',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    helpText: 'Completar si el paciente es menor de 5 años',
    colSpan: 'half',
    validation: { min: 0, max: 11 },
  },
  {
    id: 'sexo',
    label: 'Sexo',
    type: 'radio',
    page: 2,
    required: true,
    options: ['M', 'F'],
    optionLabels: { M: 'Masculino', F: 'Femenino' },
    colSpan: 'half',
  },
  {
    id: 'departamento_residencia',
    label: 'Departamento de Residencia',
    type: 'select',
    page: 2,
    required: true,
    options: departamentosGuatemala,
    colSpan: 'half',
  },
  {
    id: 'municipio_residencia',
    label: 'Municipio de Residencia',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Municipio',
    colSpan: 'half',
  },
  {
    id: 'direccion_exacta',
    label: 'Dirección Exacta',
    type: 'textarea',
    page: 2,
    required: false,
    placeholder: 'Dirección completa del paciente',
    colSpan: 'full',
    validation: { maxLength: 300 },
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 3: EMBARAZO (condicional según sexo)
  // ═══════════════════════════════════════════════════
  {
    id: 'esta_embarazada',
    label: '¿Está Embarazada?',
    type: 'radio',
    page: 3,
    required: true,
    options: ['SI', 'NO', 'N/A'],
    conditional: { dependsOn: 'sexo', showWhen: 'F' },
    colSpan: 'full',
  },
  {
    id: 'semanas_embarazo',
    label: 'Semanas de Embarazo',
    type: 'number',
    page: 3,
    required: true,
    placeholder: 'Semanas',
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { min: 1, max: 42 },
  },
  {
    id: 'fecha_probable_parto',
    label: 'Fecha Probable de Parto',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'vacuna_embarazada',
    label: 'Vacuna (en embarazada)',
    type: 'select',
    page: 3,
    required: false,
    options: ['SI', 'NO', 'N/S', 'N/A'],
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'fecha_vacunacion_embarazada',
    label: 'Fecha de Vacunación',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'vacuna_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 4: DATOS DE CONSULTA Y SINTOMATOLOGÍA
  // ═══════════════════════════════════════════════════
  {
    id: 'motivo_consulta',
    label: 'Motivo de Consulta',
    type: 'textarea',
    page: 4,
    required: true,
    placeholder: 'Describa el motivo de consulta',
    colSpan: 'full',
    validation: { minLength: 3, maxLength: 500 },
  },
  {
    id: 'fecha_inicio_sintomas',
    label: 'Fecha de Inicio de los Síntomas',
    type: 'date',
    page: 4,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'signo_fiebre',
    label: 'Fiebre',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Signos y Síntomas',
  },
  {
    id: 'signo_exantema',
    label: 'Exantema',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_manchas_koplik',
    label: 'Manchas de Koplik',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_tos',
    label: 'Tos',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_conjuntivitis',
    label: 'Conjuntivitis',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_artralgia',
    label: 'Artralgia o Artritis',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_coriza',
    label: 'Coriza o Catarro (resfriado)',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_adenopatias',
    label: 'Adenopatías',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 5: VACUNACIÓN
  // ═══════════════════════════════════════════════════
  {
    id: 'numero_dosis_spr',
    label: 'Número de Dosis SPR/SR',
    type: 'select',
    page: 5,
    required: true,
    options: ['0', '1', '2', '3', 'DESCONOCIDO'],
    helpText: 'Número de dosis de vacuna SPR o SR recibidas',
    colSpan: 'half',
  },
  {
    id: 'fecha_ultima_dosis',
    label: 'Fecha de Última Dosis',
    type: 'date',
    page: 5,
    required: false,
    helpText: 'Fecha de la última dosis de SPR/SR aplicada',
    colSpan: 'half',
    validation: { noFuture: true },
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 6: COMPLICACIONES Y HOSPITALIZACIÓN
  // ═══════════════════════════════════════════════════
  {
    id: 'hospitalizado',
    label: '¿Fue Hospitalizado?',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },
  {
    id: 'complicaciones',
    label: 'Complicaciones',
    type: 'select',
    page: 6,
    required: true,
    options: [
      'NO',
      'NEUMONÍA',
      'ENCEFALITIS',
      'DESHIDRATACIÓN',
      'OTITIS MEDIA',
      'DIARREA',
      'OTRA',
    ],
    colSpan: 'half',
  },
  {
    id: 'complicaciones_otra',
    label: 'Especifique complicación',
    type: 'text',
    page: 6,
    required: true,
    placeholder: 'Describa la complicación',
    conditional: { dependsOn: 'complicaciones', showWhen: 'OTRA' },
    colSpan: 'half',
  },
  {
    id: 'condicion_egreso',
    label: 'Condición de Egreso',
    type: 'select',
    page: 6,
    required: true,
    options: ['MEJORADO', 'GRAVE', 'MUERTO', 'N/A'],
    colSpan: 'half',
  },
  {
    id: 'fecha_defuncion',
    label: 'Fecha de Defunción',
    type: 'date',
    page: 6,
    required: true,
    conditional: { dependsOn: 'condicion_egreso', showWhen: 'MUERTO' },
    colSpan: 'half',
    validation: { noFuture: true },
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 7: MUESTRAS Y RESULTADOS DE LABORATORIO
  // ═══════════════════════════════════════════════════
  {
    id: 'fecha_laboratorios',
    label: 'Fecha que Realiza Laboratorios',
    type: 'date',
    page: 7,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'tipo_muestra',
    label: 'Tipo de Muestra',
    type: 'select',
    page: 7,
    required: true,
    options: [
      'SUERO/HISOPADO/ORINA',
      'SUERO',
      'HISOPADO NASOFARINGEO',
      'ORINA',
      'SUERO/HISOPADO',
      'SUERO/ORINA',
      'HISOPADO/ORINA',
      'OTRO',
      'N/A',
    ],
    helpText: 'Tipo de muestra enviada al laboratorio',
    colSpan: 'half',
  },
  {
    id: 'resultado_igg_numerico',
    label: 'Resultado IgG Numérico',
    type: 'text',
    page: 7,
    required: false,
    placeholder: 'Valor numérico',
    colSpan: 'half',
  },
  {
    id: 'resultado_igg_cualitativo',
    label: 'Resultado IgG Cualitativo',
    type: 'select',
    page: 7,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    colSpan: 'half',
  },
  {
    id: 'resultado_igm_numerico',
    label: 'Resultado IgM Numérico',
    type: 'text',
    page: 7,
    required: false,
    placeholder: 'Valor numérico',
    colSpan: 'half',
  },
  {
    id: 'resultado_igm_cualitativo',
    label: 'Resultado IgM Cualitativo',
    type: 'select',
    page: 7,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    colSpan: 'half',
  },
  {
    id: 'resultado_pcr_orina',
    label: 'Resultado RT-PCR Orina',
    type: 'select',
    page: 7,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    colSpan: 'half',
  },
  {
    id: 'resultado_pcr_hisopado',
    label: 'Resultado RT-PCR Hisopado',
    type: 'select',
    page: 7,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // PÁGINA 8: CONTACTOS Y CLASIFICACIÓN
  // ═══════════════════════════════════════════════════
  {
    id: 'contactos_directos',
    label: 'No. de Contactos Directos',
    type: 'number',
    page: 8,
    required: false,
    placeholder: '0',
    helpText: 'Número de contactos directos identificados',
    colSpan: 'half',
    validation: { min: 0, max: 999 },
  },
  {
    id: 'clasificacion_caso',
    label: 'Clasificación del Caso',
    type: 'select',
    page: 8,
    required: true,
    options: [
      'SOSPECHOSO',
      'CONFIRMADO',
      'DESCARTADO',
      'CLÍNICO',
      'FALSO',
      'ERROR DIAGNÓSTICO',
    ],
    helpText: 'Clasificación final del caso según protocolo',
    colSpan: 'half',
  },
  {
    id: 'observaciones',
    label: 'Observaciones',
    type: 'textarea',
    page: 8,
    required: false,
    placeholder: 'Observaciones adicionales del caso',
    colSpan: 'full',
    validation: { maxLength: 1000 },
  },
]

// Campos que se agregan automáticamente al envío
export const autoFields = [
  'registro_id',           // UUID corto generado automáticamente
  'timestamp_envio',       // Fecha y hora de envío
  'usuario_dispositivo',   // Identificador del dispositivo
]

// Obtener el total de páginas
export const getTotalPages = () => {
  return Math.max(...formFields.map(f => f.page))
}

// Obtener campos de una página específica
export const getFieldsByPage = (page) => {
  return formFields.filter(f => f.page === page)
}
