/**
 * Schema del formulario de Vigilancia Epidemiológica - Sarampión/Rubéola
 * Compatible con MSPAS EPIWEB (formato 2026) + GoData + campos IGSS adicionales
 *
 * Estructura: 9 tabs
 *   1. Datos Generales (Unidad Notificadora + fuente/investigación)
 *   2. Datos del Paciente
 *   3. Embarazo (condicional sexo=F)
 *   4. Antecedentes y Vacunación
 *   5. Datos Clínicos (síntomas + hospitalización + complicaciones)
 *   6. Factores de Riesgo
 *   7. Acciones de Respuesta
 *   8. Laboratorio
 *   9. Clasificación y Datos IGSS
 */

import { unidadesMedicasNombres } from './unidadesMedicas.js'
// etniasOptions and escolaridadOptions now inlined in formFields (aligned with MSPAS/GoData 2026)
import { ocupacionesOptions } from './mspasOcupaciones.js'
import { departamentos, getMunicipios } from './mspasMunicipios.js'
import { getPoblados } from './mspasPoblados.js'
import { getSubgerencias } from './igssOrganizacion.js'
import { paisesMundoUnicos } from './paises.js'

export const formTitle = 'Ficha de Investigación Epidemiológica'
export const formSubtitle = 'Sarampión / Rubéola — IGSS Epidemiología'
export const institutionName = 'Instituto Guatemalteco de Seguridad Social'

export const pageLabels = {
  1: 'Datos Generales',
  2: 'Datos del Paciente',
  3: 'Embarazo',
  4: 'Antecedentes y Vacunación',
  5: 'Datos Clínicos',
  6: 'Factores de Riesgo',
  7: 'Acciones de Respuesta',
  8: 'Laboratorio',
  9: 'Clasificación y Datos IGSS',
}

export const diagnosticosMap = {
  'B055 - Sarampión confirmado por laboratorio': 'B055',
  'B056 - Sarampión confirmado por nexo epidemiológico': 'B056',
  'B057 - Sarampión confirmado clínicamente': 'B057',
  'B059 - Sospechoso de Sarampión': 'B059',
  'B069 - Rubéola sin complicaciones': 'B069',
}

export const departamentosGuatemala = departamentos

// Re-export for cascading selects
export { getMunicipios, getPoblados }

export const formFields = [
  // ═══════════════════════════════════════════════════
  // TAB 1: DATOS GENERALES — Unidad Notificadora
  // ═══════════════════════════════════════════════════
  {
    id: 'diagnostico_registrado',
    label: 'Diagnóstico Registrado',
    type: 'select',
    page: 1,
    required: true,
    options: Object.keys(diagnosticosMap),
    autoMap: 'codigo_cie10',
    helpText: 'Seleccione el diagnóstico CIE-10 registrado en la consulta',
    colSpan: 'half',
  },
  {
    id: 'codigo_cie10',
    label: 'Código CIE-10',
    type: 'text',
    page: 1,
    required: false,
    placeholder: 'Se asigna automáticamente',
    colSpan: 'half',
    readOnly: true,
    autoFrom: 'diagnostico_registrado',
    validation: { maxLength: 10 },
  },
  {
    id: 'diagnostico_sospecha',
    label: 'Diagnóstico de Sospecha',
    type: 'checkbox',
    page: 1,
    required: false,
    options: [
      'Sarampión',
      'Rubéola',
      'Dengue',
      'Otra Arbovirosis',
      'Otra febril exantemática',
      'Caso altamente sospechoso de Sarampión',
    ],
    helpText: 'Se deriva automáticamente del diagnóstico CIE-10 seleccionado. Puede agregar sospechas adicionales (ej: Dengue).',
    colSpan: 'full',
  },
  {
    id: 'diagnostico_sospecha_otro',
    label: 'Especifique diagnóstico de sospecha',
    type: 'text',
    page: 1,
    required: false,
    placeholder: 'Especifique el diagnóstico',
    conditional: { dependsOn: 'diagnostico_sospecha', showWhen: ['Otra Arbovirosis', 'Otra febril exantemática'] },
    colSpan: 'half',
  },
  {
    id: 'unidad_medica',
    label: 'Unidad Médica que Reporta',
    type: 'select',
    page: 1,
    required: true,
    options: unidadesMedicasNombres,
    searchable: true,
    helpText: 'Unidad médica del IGSS que reporta el caso',
    colSpan: 'half',
  },
  {
    id: 'unidad_medica_otra',
    label: 'Especifique la unidad médica',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Nombre de la unidad médica',
    conditional: { dependsOn: 'unidad_medica', showWhen: 'OTRA' },
    colSpan: 'half',
  },
  // es_seguro_social y establecimiento_privado se hardcodean automáticamente al enviar
  // IGSS siempre es Seguro Social (SI) y nunca establecimiento privado (NO)
  {
    id: 'es_seguro_social',
    type: 'radio',
    page: 1,
    options: ['SI', 'NO'],
    hidden: true,
  },
  {
    id: 'establecimiento_privado',
    type: 'radio',
    page: 1,
    options: ['SI', 'NO'],
    hidden: true,
  },
  {
    id: 'establecimiento_privado_nombre',
    type: 'text',
    page: 1,
    hidden: true,
  },
  {
    id: 'fecha_notificacion',
    label: 'Fecha de Notificación',
    type: 'date',
    page: 1,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'fecha_registro_diagnostico',
    label: 'Fecha de Consulta',
    type: 'date',
    page: 1,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'semana_epidemiologica',
    label: 'Semana Epidemiológica',
    type: 'number',
    page: 1,
    required: true,
    placeholder: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 1, max: 53 },
    autoCalculate: 'epiWeek',
    dependsOnDate: 'fecha_notificacion',
    helpText: 'Se calcula automáticamente según la fecha de notificación (sistema MMWR/CDC)',
    readOnly: true,
  },
  {
    id: 'area_salud_mspas',
    label: 'Departamento',
    type: 'select',
    page: 1,
    required: true,
    options: departamentosGuatemala,
    searchable: true,
    colSpan: 'half',
    sectionTitle: 'Ubicación MSPAS',
  },
  {
    id: 'distrito_salud_mspas',
    label: 'Municipio',
    type: 'select',
    page: 1,
    required: true,
    options: [],
    searchable: true,
    cascadeFrom: 'area_salud_mspas',
    colSpan: 'half',
  },
  {
    id: 'servicio_reporta',
    label: 'Servicio que Reporta',
    type: 'select',
    page: 1,
    required: false,
    options: ['EMERGENCIA', 'CONSULTA EXTERNA', 'ENCAMAMIENTO', 'OTRO'],
    colSpan: 'half',
  },
  {
    id: 'nom_responsable',
    label: 'Responsable de Notificación',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Nombre del responsable',
    colSpan: 'half',
    sectionTitle: 'Responsable',
  },
  {
    id: 'cargo_responsable',
    label: 'Cargo',
    type: 'select',
    page: 1,
    required: true,
    options: ['Epidemiólogo', 'Médico', 'Enfermera profesional', 'Otro'],
    colSpan: 'half',
  },
  {
    id: 'telefono_responsable',
    label: 'Teléfono',
    type: 'phone',
    page: 1,
    required: false,
    placeholder: 'Teléfono del responsable',
    colSpan: 'half',
  },
  {
    id: 'correo_responsable',
    label: 'Correo Electrónico',
    type: 'email',
    page: 1,
    required: true,
    placeholder: 'correo@ejemplo.com',
    colSpan: 'half',
    validation: { maxLength: 150 },
  },
  {
    id: 'envio_ficha',
    label: '¿Enviaron Ficha Epidemiológica?',
    type: 'radio',
    page: 1,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'full',
    hidden: true,
  },

  // Fuente de Notificación: hardcodeado "Servicio de Salud" (IGSS siempre reporta desde sus servicios)
  // No es obligatorio en GoData (2/5 casos reales lo tienen vacío)
  {
    id: 'fuente_notificacion',
    type: 'select',
    page: 1,
    options: ['Servicio de Salud'],
    hidden: true,
  },
  {
    id: 'fuente_notificacion_otra',
    type: 'text',
    page: 1,
    hidden: true,
  },
  {
    id: 'fecha_visita_domiciliaria',
    label: 'Fecha Visita Domiciliaria',
    type: 'date',
    page: 1,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },
  {
    id: 'fecha_inicio_investigacion',
    label: 'Fecha Inicio Investigación',
    type: 'date',
    page: 1,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },
  {
    id: 'busqueda_activa',
    label: 'Búsqueda Activa',
    type: 'select',
    page: 1,
    required: false,
    options: [
      'Retrospectiva en el servicio',
      'Comunidad',
      'Otras',
    ],
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'busqueda_activa_otra',
    label: 'Otra búsqueda activa',
    type: 'text',
    page: 1,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'busqueda_activa', showWhen: 'Otras' },
    colSpan: 'half',
    hidden: true,
  },

  // ═══════════════════════════════════════════════════
  // TAB 2: DATOS DEL PACIENTE
  // ═══════════════════════════════════════════════════
  {
    id: 'afiliacion',
    label: 'Número de Afiliación',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Número de afiliación del paciente',
    helpText: 'Número de afiliación IGSS o número de registro',
    colSpan: 'half',
    validation: { minLength: 3, maxLength: 20 },
  },
  {
    id: 'tipo_identificacion',
    label: 'Tipo de Identificación',
    type: 'select',
    page: 2,
    required: false,
    options: ['DPI', 'PASAPORTE', 'OTRO'],
    colSpan: 'half',
  },
  {
    id: 'numero_identificacion',
    label: 'Número de Identificación',
    type: 'text',
    page: 2,
    required: false,
    placeholder: 'Número de DPI, pasaporte u otro',
    colSpan: 'half',
    validation: { maxLength: 30, byType: 'identificacion' },
  },
  {
    id: 'nombres',
    label: 'Nombres',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Nombres del paciente',
    colSpan: 'half',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    id: 'apellidos',
    label: 'Apellidos',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Apellidos del paciente',
    colSpan: 'half',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    id: 'sexo',
    label: 'Sexo',
    type: 'radio',
    page: 2,
    required: true,
    options: ['M', 'F'],
    optionLabels: { M: 'Masculino', F: 'Femenino' },
    colSpan: 'half',
  },
  {
    id: 'fecha_nacimiento',
    label: 'Fecha de Nacimiento',
    type: 'date',
    page: 2,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
    sectionTitle: 'Edad',
  },
  {
    id: 'edad_anios',
    label: 'Edad en Años',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    colSpan: 'half',
    validation: { min: 0, max: 120 },
    helpText: 'Se calcula automáticamente desde fecha de nacimiento',
    readOnly: true,
  },
  {
    id: 'edad_meses',
    label: 'Edad en Meses',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    helpText: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 0, max: 11 },
    readOnly: true,
  },
  {
    id: 'edad_dias',
    label: 'Edad en Días',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    helpText: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 0, max: 31 },
    readOnly: true,
  },
  {
    id: 'pueblo_etnia',
    label: 'Pueblo / Etnia',
    type: 'select',
    page: 2,
    required: true,
    options: [
      'Ladino',
      'Maya',
      'Garífuna',
      'Xinca',
      'Extranjero',
      'Desconocido',
    ],
    colSpan: 'half',
    sectionTitle: 'Datos Sociodemográficos',
  },
  {
    id: 'comunidad_linguistica',
    label: 'Comunidad Lingüística',
    type: 'select',
    page: 2,
    required: false,
    searchable: true,
    options: [
      "Achi'", "Akateka", "Awakateka", "Ch'orti'", "Chalchiteka", "Chuj",
      "Garífuna", "Itza'", "Ixil", "Jakalteka", "Kaqchikel", "K'iche'",
      "Mam", "Mopan", "Poqomam", "Poqomchi'", "Q'anjob'al", "Q'eqchi'",
      "Sakapulteka", "Sipakapense", "Tektiteka", "Tz'utujil", "Uspanteka",
      "Otra", "No indica",
    ],
    conditional: { dependsOn: 'pueblo_etnia', showWhen: 'Maya' },
    colSpan: 'half',
  },
  {
    id: 'es_migrante',
    label: '¿Es migrante?',
    type: 'radio',
    page: 2,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'ocupacion',
    label: 'Ocupación',
    type: 'select',
    page: 2,
    required: true,
    options: ocupacionesOptions,
    searchable: true,
    colSpan: 'half',
  },
  {
    id: 'escolaridad',
    label: 'Escolaridad',
    type: 'select',
    page: 2,
    required: true,
    options: [
      'No aplica',
      'Pre Primaria',
      'Primaria',
      'Básicos',
      'Diversificado',
      'Universitario',
      'Postgrado',
      'Ninguna',
      'Desconocida',
    ],
    colSpan: 'half',
  },
  {
    id: 'pais_residencia',
    label: 'País de Residencia',
    type: 'select',
    page: 2,
    required: false,
    searchable: true,
    defaultValue: 'GUATEMALA',
    options: [
      'GUATEMALA',
      // Centroamérica
      'MÉXICO', 'HONDURAS', 'EL SALVADOR', 'BELICE', 'NICARAGUA', 'COSTA RICA', 'PANAMÁ',
      // Caribe
      'REPÚBLICA DOMINICANA', 'HAITÍ', 'CUBA', 'JAMAICA', 'PUERTO RICO',
      // Sudamérica
      'COLOMBIA', 'VENEZUELA', 'BRASIL', 'ARGENTINA', 'PERÚ', 'CHILE', 'ECUADOR', 'BOLIVIA', 'URUGUAY', 'PARAGUAY',
      // Norteamérica
      'ESTADOS UNIDOS', 'CANADÁ',
      // Europa
      'ESPAÑA', 'FRANCIA', 'ITALIA', 'ALEMANIA', 'REINO UNIDO',
      // Asia
      'CHINA', 'INDIA', 'JAPÓN', 'COREA DEL SUR',
      // Otro
      'OTRO',
    ],
    colSpan: 'half',
    sectionTitle: 'Residencia',
  },
  {
    id: 'departamento_residencia',
    label: 'Departamento de Residencia',
    type: 'select',
    page: 2,
    required: true,
    options: departamentosGuatemala,
    colSpan: 'half',
  },
  {
    id: 'municipio_residencia',
    label: 'Municipio de Residencia',
    type: 'select',
    page: 2,
    required: true,
    options: [], // Se llena dinámicamente según departamento
    searchable: true,
    cascadeFrom: 'departamento_residencia',
    colSpan: 'half',
  },
  {
    id: 'poblado',
    label: 'Poblado / Localidad',
    type: 'select',
    page: 2,
    required: false,
    options: [], // Se llena dinámicamente según departamento + municipio
    searchable: true,
    cascadeFrom: 'municipio_residencia',
    colSpan: 'half',
  },
  {
    id: 'direccion_exacta',
    label: 'Dirección',
    type: 'textarea',
    page: 2,
    required: false,
    placeholder: 'Dirección del paciente',
    colSpan: 'full',
    validation: { maxLength: 300 },
  },
  {
    id: 'nombre_encargado',
    label: 'Nombre de la madre, padre o encargado',
    type: 'text',
    page: 2,
    required: false,
    placeholder: 'Nombre del encargado(a) del paciente',
    colSpan: 'half',
    sectionTitle: 'Encargado',
  },
  {
    id: 'parentesco_tutor',
    label: 'Parentesco del Encargado',
    type: 'select',
    page: 2,
    required: false,
    options: ['Madre', 'Padre', 'Abuelo/a', 'Tío/a', 'Hermano/a', 'Tutor Legal', 'Otro'],
    colSpan: 'half',
  },
  {
    id: 'tipo_id_tutor',
    label: 'Tipo de Identificación del Encargado',
    type: 'select',
    page: 2,
    required: false,
    options: ['DPI', 'PASAPORTE', 'OTRO'],
    colSpan: 'half',
  },
  {
    id: 'numero_id_tutor',
    label: 'Número de Identificación del Encargado',
    type: 'text',
    page: 2,
    required: false,
    placeholder: 'Número de DPI, pasaporte u otro',
    colSpan: 'half',
    validation: { maxLength: 30 },
  },
  {
    id: 'telefono_paciente',
    label: 'Teléfono del Paciente',
    type: 'phone',
    page: 2,
    required: true,
    placeholder: 'Teléfono del paciente',
    colSpan: 'half',
  },
  {
    id: 'telefono_encargado',
    label: 'Teléfono del Encargado',
    type: 'phone',
    page: 2,
    required: false,
    placeholder: 'Teléfono del encargado',
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // TAB 3: EMBARAZO (condicional sexo=F)
  // ═══════════════════════════════════════════════════
  {
    id: 'esta_embarazada',
    label: '¿Está Embarazada?',
    type: 'radio',
    page: 3,
    required: true,
    options: ['SI', 'NO', 'N/A'],
    conditional: { dependsOn: 'sexo', showWhen: 'F' },
    colSpan: 'full',
  },
  {
    id: 'lactando',
    label: '¿Está Lactando?',
    type: 'radio',
    page: 3,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'sexo', showWhen: 'F' },
    colSpan: 'full',
  },
  {
    id: 'semanas_embarazo',
    label: 'Semanas de Embarazo',
    type: 'number',
    page: 3,
    required: true,
    placeholder: 'Semanas',
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { min: 1, max: 42 },
  },
  {
    id: 'trimestre_embarazo',
    label: 'Trimestre',
    type: 'select',
    page: 3,
    required: false,
    options: ['1', '2', '3'],
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    readOnly: true,
    helpText: 'Se calcula automáticamente desde las semanas de embarazo',
    autoCalculate: 'trimestre',
    dependsOnField: 'semanas_embarazo',
  },
  {
    id: 'fecha_probable_parto',
    label: 'Fecha Probable de Parto',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'vacuna_embarazada',
    label: 'Vacuna (en embarazada)',
    type: 'select',
    page: 3,
    required: false,
    options: ['SI', 'NO', 'N/S', 'N/A'],
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'fecha_vacunacion_embarazada',
    label: 'Fecha de Vacunación',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'vacuna_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
    hidden: true,
  },

  // ═══════════════════════════════════════════════════
  // TAB 4: ANTECEDENTES Y VACUNACIÓN
  // ═══════════════════════════════════════════════════
  {
    id: 'vacunado',
    label: 'Vacunado contra Sarampión',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO/VERBAL'],
    colSpan: 'half',
    sectionTitle: 'Antecedentes de Vacunación',
  },
  {
    id: 'fuente_info_vacuna',
    label: 'Fuente de Información',
    type: 'select',
    page: 4,
    required: true,
    options: [
      'Carné de Vacunación',
      'Registro Único de Vacunación',
    ],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'sector_vacunacion',
    label: 'Sector de Vacunación',
    type: 'select',
    page: 4,
    required: false,
    options: ['MSPAS', 'IGSS', 'Privado'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
  },

  // SPR
  {
    id: 'dosis_spr',
    label: 'Número de Dosis SPR',
    type: 'select',
    page: 4,
    required: false,
    options: ['1', '2', '3', 'Más de 3', 'No recuerda'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    sectionTitle: 'SPR — Sarampión Paperas Rubéola',
  },
  {
    id: 'fecha_ultima_spr',
    label: 'Fecha Última Dosis SPR',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
  },

  // SR
  {
    id: 'dosis_sr',
    label: 'Número de Dosis SR',
    type: 'select',
    page: 4,
    required: false,
    options: ['1', '2', '3', 'Más de 3', 'No recuerda'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    sectionTitle: 'SR — Sarampión Rubéola',
  },
  {
    id: 'fecha_ultima_sr',
    label: 'Fecha Última Dosis SR',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
  },

  // SPRV
  {
    id: 'dosis_sprv',
    label: 'Número de Dosis SPRV',
    type: 'select',
    page: 4,
    required: false,
    options: ['1', '2', '3', 'Más de 3', 'No recuerda'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    sectionTitle: 'SPRV — Sarampión Paperas Rubéola Varicela',
  },
  {
    id: 'fecha_ultima_sprv',
    label: 'Fecha Última Dosis SPRV',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
  },

  // Campos legacy (compatibilidad retroactiva — ocultos en UI pero almacenados)
  {
    id: 'tipo_vacuna',
    label: 'Tipo de Vacuna',
    type: 'select',
    page: 4,
    required: false,
    options: [
      'Antisarampinosa',
      'Antirubeólica',
      'SR Sarampión Rubéola',
      'SRP Sarampión Rubéola Paperas',
      'No recuerda',
    ],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'numero_dosis_spr',
    label: 'Número de Dosis (legacy)',
    type: 'select',
    page: 4,
    required: false,
    options: ['1 dosis', '2 dosis', '3 dosis', 'Más de 3 dosis', 'No recuerda'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'fecha_ultima_dosis',
    label: 'Fecha Última Dosis (legacy)',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
    hidden: true,
  },
  {
    id: 'observaciones_vacuna',
    label: 'Observaciones de Vacunación',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Si se perdió el carné, anotar información verbal',
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'full',
    hidden: true,
  },

  // Antecedentes Médicos
  {
    id: 'tiene_antecedentes_medicos',
    label: '¿Tiene antecedentes médicos relevantes?',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'full',
    sectionTitle: 'Antecedentes Médicos',
  },
  {
    id: 'antecedentes_medicos_detalle',
    label: 'Detalle de antecedentes médicos',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Describa los antecedentes médicos relevantes',
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'full',
    validation: { maxLength: 500 },
  },
  {
    id: 'antecedente_desnutricion',
    label: 'Desnutrición',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'antecedente_inmunocompromiso',
    label: 'Inmunocompromiso',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'antecedente_vih',
    label: 'VIH / SIDA',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'antecedente_cancer',
    label: 'Cáncer / Neoplasia',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'tipo_cancer',
    label: 'Tipo de cáncer',
    type: 'text',
    page: 4,
    required: false,
    conditional: { dependsOn: 'antecedente_cancer', showWhen: 'SI' },
    colSpan: 'full',
    validation: { maxLength: 200 },
  },
  {
    id: 'antecedente_enfermedad_cronica',
    label: 'Enfermedad Crónica',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_antecedentes_medicos', showWhen: 'SI' },
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // TAB 5: DATOS CLÍNICOS
  // ═══════════════════════════════════════════════════

  // --- Conocimiento del Caso ---
  {
    id: 'fecha_inicio_sintomas',
    label: 'Fecha Inicio Síntomas',
    type: 'date',
    page: 5,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    sectionTitle: 'Conocimiento del Caso',
  },
  {
    id: 'fecha_captacion',
    label: 'Fecha de Captación',
    type: 'date',
    page: 5,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },

  // --- Circunstancias de Exposición ---
  {
    id: 'fecha_inicio_erupcion',
    label: 'Fecha Inicio Erupción',
    type: 'date',
    page: 5,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    sectionTitle: 'Circunstancias de Exposición',
  },
  {
    id: 'sitio_inicio_erupcion',
    label: 'Sitio de Inicio de Erupción',
    type: 'select',
    page: 5,
    required: false,
    options: [
      'Retroauricular',
      'Cara',
      'Cuello',
      'Tórax',
      'Otro',
    ],
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'sitio_inicio_erupcion_otro',
    label: 'Otro sitio de erupción',
    type: 'text',
    page: 5,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'sitio_inicio_erupcion', showWhen: 'Otro' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'fecha_inicio_fiebre',
    label: 'Fecha Inicio Fiebre',
    type: 'date',
    page: 5,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'temperatura_celsius',
    label: 'Temperatura °C',
    type: 'number',
    page: 5,
    required: false,
    placeholder: 'Ej: 38.5',
    colSpan: 'half',
    validation: { min: 35, max: 42 },
    step: '0.1',
    helpText: 'Temperatura en grados Celsius (ej: 38.5)',
  },

  // --- Signos y Síntomas (expandidos a SI/NO/DESCONOCIDO) ---
  {
    id: 'signo_fiebre',
    label: 'Fiebre',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
    sectionTitle: 'Signos y Síntomas',
  },
  {
    id: 'signo_exantema',
    label: 'Exantema Maculopapular (No vesicular)',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_manchas_koplik',
    label: 'Manchas de Koplik',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_tos',
    label: 'Tos',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_conjuntivitis',
    label: 'Conjuntivitis',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_coriza',
    label: 'Coriza (catarro)',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_adenopatias',
    label: 'Adenopatías',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'signo_artralgia',
    label: 'Artralgia o Artritis',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
  },
  {
    id: 'asintomatico',
    label: 'Asintomático',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
    hidden: true,
  },

  // --- Hospitalización y Defunción ---
  {
    id: 'hospitalizado',
    label: '¿Fue Hospitalizado?',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
    sectionTitle: 'Hospitalización y Defunción',
  },
  {
    id: 'hosp_nombre',
    label: 'Nombre del Hospital',
    type: 'select',
    page: 5,
    required: true,
    searchable: true,
    options: [...unidadesMedicasNombres, 'OTRO HOSPITAL'],
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'hosp_fecha',
    label: 'Fecha de Hospitalización',
    type: 'date',
    page: 5,
    required: true,
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'no_registro_medico',
    label: 'No. de Registro Médico',
    type: 'text',
    page: 5,
    required: false,
    placeholder: 'Número de registro médico',
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'condicion_egreso',
    label: 'Condición de Egreso',
    type: 'select',
    page: 5,
    required: false,
    options: ['MEJORADO', 'GRAVE', 'MUERTO'],
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'fecha_egreso',
    label: 'Fecha de Egreso',
    type: 'date',
    page: 5,
    required: false,
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },
  {
    id: 'medico_certifica_defuncion',
    label: 'Médico que Certifica Defunción',
    type: 'text',
    page: 5,
    required: false,
    placeholder: 'Nombre del médico',
    conditional: { dependsOn: 'condicion_egreso', showWhen: 'MUERTO' },
    colSpan: 'half',
  },
  {
    id: 'motivo_consulta',
    label: 'Motivo de Consulta / Observaciones Clínicas',
    type: 'textarea',
    page: 5,
    required: false,
    placeholder: 'Describa el motivo de consulta u observaciones',
    colSpan: 'full',
    validation: { maxLength: 500 },
    hidden: true,
  },

  // --- Complicaciones ---
  {
    id: 'tiene_complicaciones',
    label: '¿Presenta complicaciones?',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'full',
    sectionTitle: 'Complicaciones',
  },
  {
    id: 'comp_neumonia',
    label: 'Neumonía',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_encefalitis',
    label: 'Encefalitis',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_diarrea',
    label: 'Diarrea',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_trombocitopenia',
    label: 'Trombocitopenia',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_otitis',
    label: 'Otitis',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_ceguera',
    label: 'Ceguera',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'comp_otra_texto',
    label: 'Otra complicación',
    type: 'text',
    page: 5,
    required: false,
    placeholder: 'Especifique otra complicación',
    conditional: { dependsOn: 'tiene_complicaciones', showWhen: 'SI' },
    colSpan: 'full',
    validation: { maxLength: 300 },
  },

  // --- Aislamiento ---
  {
    id: 'aislamiento_respiratorio',
    label: '¿Se realizó aislamiento respiratorio?',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
    sectionTitle: 'Aislamiento',
  },
  {
    id: 'fecha_aislamiento',
    label: 'Fecha de Aislamiento',
    type: 'date',
    page: 5,
    required: false,
    conditional: { dependsOn: 'aislamiento_respiratorio', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },

  // ═══════════════════════════════════════════════════
  // TAB 6: FACTORES DE RIESGO
  // ═══════════════════════════════════════════════════
  {
    id: 'contacto_sospechoso_7_23',
    label: 'Tuvo contacto con un caso sospechoso o confirmado entre 7-23 días antes del inicio del exantema/rash',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'full',
  },
  {
    id: 'caso_sospechoso_comunidad_3m',
    label: 'Hubo algún caso sospechoso en la comunidad o municipio antes de este caso, en los últimos 3 meses',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'full',
  },
  {
    id: 'viajo_7_23_previo',
    label: 'Viajó durante los 7-23 días previos al inicio de la erupción',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },

  // Viaje estructurado (reemplaza destino_viaje texto libre)
  {
    id: 'viaje_pais',
    label: 'País de Destino del Viaje',
    type: 'select',
    page: 6,
    required: false,
    searchable: true,
    options: paisesMundoUnicos,
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'viaje_pais_otro',
    label: 'Especifique país',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Nombre del país',
    conditional: { dependsOn: 'viaje_pais', showWhen: 'OTRO' },
    colSpan: 'half',
    validation: { maxLength: 80 },
  },
  {
    id: 'viaje_departamento',
    label: 'Departamento de Destino',
    type: 'select',
    page: 6,
    required: false,
    searchable: true,
    options: departamentosGuatemala,
    conditional: { dependsOn: 'viaje_pais', showWhen: 'GUATEMALA' },
    colSpan: 'half',
  },
  {
    id: 'viaje_municipio',
    label: 'Municipio de Destino',
    type: 'select',
    page: 6,
    required: false,
    searchable: true,
    options: [], // Se llena dinámicamente según viaje_departamento
    cascadeFrom: 'viaje_departamento',
    conditional: { dependsOn: 'viaje_pais', showWhen: 'GUATEMALA' },
    colSpan: 'half',
  },
  {
    id: 'viaje_ciudad_destino',
    label: 'Ciudad / Estado / Región de destino',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Ej: Cancún, Quintana Roo / Miami, Florida / Madrid',
    helpText: 'Especifique la ciudad, estado o región visitada dentro del país',
    conditional: {
      dependsOn: 'viaje_pais',
      // Aparece para cualquier país seleccionado EXCEPTO GUATEMALA (usa cascade
      // depto→municipio arriba). Con OTRO también se muestra para que el usuario
      // pueda indicar país (viaje_pais_otro) Y ciudad/región.
      showWhenNot: ['GUATEMALA', ''],
    },
    colSpan: 'full',
    validation: { maxLength: 120 },
  },
  {
    id: 'viaje_fecha_salida',
    label: 'Fecha de Salida',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
  },
  {
    id: 'viaje_fecha_entrada',
    label: 'Fecha de Regreso',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, flexibleParse: true },
  },
  {
    id: 'familiar_viajo_exterior',
    label: '¿Algún familiar viajó al exterior recientemente?',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'familiar_fecha_retorno',
    label: 'Fecha de Retorno del Familiar',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'familiar_viajo_exterior', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },

  // Campo legacy (compatibilidad retroactiva)
  {
    id: 'destino_viaje',
    label: '¿A dónde viajó? (legacy)',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Indique el destino del viaje',
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'full',
    hidden: true,
  },

  {
    id: 'contacto_enfermo_catarro',
    label: '¿Tuvo contacto con algún enfermo con catarro o erupción?',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'full',
    hidden: true,
  },
  {
    id: 'contacto_embarazada',
    label: '¿Tuvo contacto con una embarazada?',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'full',
  },
  {
    id: 'fuente_posible_contagio',
    label: 'Fuente Posible de Contagio',
    type: 'select',
    page: 6,
    required: false,
    options: [
      'Contacto en el hogar',
      'Servicio de Salud',
      'Institución Educativa',
      'Espacio Público',
      'Evento Masivo',
      'Transporte Internacional',
      'Comunidad',
      'Desconocido',
      'Otro',
    ],
    colSpan: 'half',
  },
  {
    id: 'fuente_contagio_otro',
    label: 'Otra fuente de contagio',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Especifique la fuente de contagio',
    conditional: { dependsOn: 'fuente_posible_contagio', showWhen: 'Otro' },
    colSpan: 'half',
    validation: { maxLength: 200 },
  },

  // ═══════════════════════════════════════════════════
  // TAB 7: ACCIONES DE RESPUESTA
  // ═══════════════════════════════════════════════════

  // Búsqueda Activa
  {
    id: 'bai_realizada',
    label: '¿Se realizó Búsqueda Activa Institucional (BAI)?',
    type: 'radio',
    page: 7,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Búsqueda Activa',
  },
  {
    id: 'bai_casos_sospechosos',
    label: 'Casos sospechosos encontrados en BAI',
    type: 'number',
    page: 7,
    required: false,
    placeholder: '0',
    conditional: { dependsOn: 'bai_realizada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { min: 0, max: 9999 },
  },
  {
    id: 'bac_realizada',
    label: '¿Se realizó Búsqueda Activa Comunitaria (BAC)?',
    type: 'radio',
    page: 7,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'bac_casos_sospechosos',
    label: 'Casos sospechosos encontrados en BAC',
    type: 'number',
    page: 7,
    required: false,
    placeholder: '0',
    conditional: { dependsOn: 'bac_realizada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { min: 0, max: 9999 },
    hidden: true,
  },

  // Vacunación de Respuesta
  {
    id: 'vacunacion_bloqueo',
    label: '¿Se realizó vacunación de bloqueo?',
    type: 'radio',
    page: 7,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Vacunación de Respuesta',
    hidden: true,
  },
  {
    id: 'monitoreo_rapido_vacunacion',
    label: '¿Se realizó monitoreo rápido de vacunación?',
    type: 'radio',
    page: 7,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'vacunacion_barrido',
    label: '¿Se realizó vacunación de barrido?',
    type: 'radio',
    page: 7,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
    hidden: true,
  },

  // Vitamina A
  {
    id: 'vitamina_a_administrada',
    label: '¿Se administró Vitamina A?',
    type: 'radio',
    page: 7,
    required: false,
    requiredIf: (fd) => {
      // Solo requerido si hay edad registrada Y es < 5 años.
      // Vacío o no-numérico → no bloquear el avance.
      const raw = fd.edad_anios
      if (raw === undefined || raw === null || String(raw).trim() === '') return false
      const anios = Number(raw)
      return !isNaN(anios) && anios < 5
    },
    requiredIfMessage: 'Obligatorio para menores de 5 años',
    options: ['SI', 'NO', 'DESCONOCIDO'],
    colSpan: 'half',
    sectionTitle: 'Vitamina A',
  },
  {
    id: 'vitamina_a_dosis',
    label: 'Número de Dosis de Vitamina A recibidas',
    type: 'select',
    page: 7,
    required: false,
    options: ['1', '2', '3', '4 o más', 'Desconocido'],
    conditional: { dependsOn: 'vitamina_a_administrada', showWhen: 'SI' },
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // TAB 8: LABORATORIO
  // ═══════════════════════════════════════════════════
  {
    id: 'recolecto_muestra',
    label: 'Recolectó Muestra',
    type: 'radio',
    page: 8,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
    sectionTitle: 'Muestras de Laboratorio',
  },
  {
    id: 'motivo_no_recoleccion',
    label: '¿Por qué no se recolectó la muestra?',
    type: 'select',
    page: 8,
    required: false,
    options: [
      'Paciente rechazó',
      'No había insumos',
      'Muestra inadecuada',
      'Tiempo de recolección excedido',
      'Paciente fallecido antes de recolección',
      'Por Nexo epidemiológico',
      'Otra razón',
    ],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'NO' },
    colSpan: 'full',
  },
  {
    id: 'motivo_no_recoleccion_otro',
    label: 'Especifique motivo',
    type: 'text',
    page: 8,
    required: false,
    requiredIf: (fd) => fd.motivo_no_recoleccion === 'Otra razón',
    requiredIfMessage: 'Debe especificar el motivo cuando selecciona "Otra razón"',
    placeholder: 'Describa el motivo',
    conditional: { dependsOn: 'motivo_no_recoleccion', showWhen: 'Otra razón' },
    colSpan: 'half',
  },
  {
    id: 'muestra_suero',
    label: 'Suero',
    type: 'radio',
    page: 8,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_suero_fecha',
    label: 'Fecha Recolección Suero',
    type: 'date',
    page: 8,
    required: true,
    conditional: { dependsOn: 'muestra_suero', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'muestra_hisopado',
    label: 'Hisopado Nasofaríngeo',
    type: 'radio',
    page: 8,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_hisopado_fecha',
    label: 'Fecha Recolección Hisopado',
    type: 'date',
    page: 8,
    required: true,
    conditional: { dependsOn: 'muestra_hisopado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'muestra_orina',
    label: 'Orina',
    type: 'radio',
    page: 8,
    required: true,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_orina_fecha',
    label: 'Fecha Recolección Orina',
    type: 'date',
    page: 8,
    required: true,
    conditional: { dependsOn: 'muestra_orina', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'muestra_otra',
    label: 'Otra Muestra',
    type: 'radio',
    page: 8,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_otra_descripcion',
    label: 'Descripción Otra Muestra',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Tipo de muestra',
    conditional: { dependsOn: 'muestra_otra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_otra_fecha',
    label: 'Fecha Recolección Otra Muestra',
    type: 'date',
    page: 8,
    required: false,
    conditional: { dependsOn: 'muestra_otra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'antigeno_prueba',
    label: 'Antígeno',
    type: 'select',
    page: 8,
    required: false,
    options: ['Sarampión', 'Rubéola', 'Dengue', 'Otros'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'antigeno_otro',
    label: 'Otro Antígeno',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'antigeno_prueba', showWhen: 'Otros' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_prueba',
    label: 'Resultado de Prueba',
    type: 'select',
    page: 8,
    required: false,
    options: ['Negativo', 'Positivo', 'Muestra Inadecuada', 'Indeterminada'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'fecha_recepcion_laboratorio',
    label: 'Fecha Recepción en Laboratorio',
    type: 'date',
    page: 8,
    required: false,
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },
  {
    id: 'fecha_resultado_laboratorio',
    label: 'Fecha de Resultado',
    type: 'date',
    page: 8,
    required: false,
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },
  // Resultados detallados (mantener compatibilidad)
  {
    id: 'resultado_igg_cualitativo',
    label: 'Resultado IgG Cualitativo',
    type: 'select',
    page: 8,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_igg_numerico',
    label: 'Resultado IgG Numérico',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Valor numérico',
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_igm_cualitativo',
    label: 'Resultado IgM Cualitativo',
    type: 'select',
    page: 8,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_igm_numerico',
    label: 'Resultado IgM Numérico',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Valor numérico',
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_pcr_orina',
    label: 'Resultado RT-PCR Orina',
    type: 'select',
    page: 8,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },
  {
    id: 'resultado_pcr_hisopado',
    label: 'Resultado RT-PCR Hisopado',
    type: 'select',
    page: 8,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    hidden: true,
  },

  // Formato 2026 — campos adicionales laboratorio
  {
    id: 'motivo_no_3_muestras',
    label: 'Motivo por el que no se tomaron las 3 muestras',
    type: 'select',
    page: 8,
    required: false,
    options: [
      'No corresponde a grupo prioritario',
      'Por nexo epidemiológico',
      'Paciente con diagnóstico clínico',
      'Otro',
    ],
    helpText: 'Solo llenar si NO se tomaron las 3 muestras (suero, hisopado y orina)',
    conditional: {
      dependsOn: 'recolecto_muestra',
      showWhen: 'SI',
      additionalCheck: (fd) => {
        const s = fd.muestra_suero === 'SI'
        const h = fd.muestra_hisopado === 'SI'
        const o = fd.muestra_orina === 'SI'
        return !(s && h && o)
      },
    },
    colSpan: 'full',
    sectionTitle: 'Formato 2026',
  },
  {
    id: 'motivo_no_3_muestras_otro',
    label: 'Especifique otro motivo',
    type: 'text',
    page: 8,
    required: false,
    requiredIf: (fd) => fd.motivo_no_3_muestras === 'Otro',
    requiredIfMessage: 'Debe especificar el motivo cuando selecciona "Otro"',
    placeholder: 'Describa el motivo',
    conditional: { dependsOn: 'motivo_no_3_muestras', showWhen: 'Otro' },
    colSpan: 'full',
    validation: { maxLength: 500 },
  },
  {
    id: 'lab_muestras_json',
    label: 'Resultados Detallados por Muestra',
    type: 'lab_matrix',
    page: 8,
    required: false,
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'full',
    sectionTitle: 'Resultados Detallados por Muestra (Formato 2026)',
    helpText: 'Ingrese los resultados de cada muestra tomada',
  },

  // Secuenciación (oculta en frontend — se mantiene en BD para compatibilidad)
  {
    id: 'secuenciacion_resultado',
    label: 'Resultado de Secuenciación',
    type: 'select',
    page: 8,
    required: false,
    options: ['B3', 'D4', 'D8', 'H1', '1E', '2B', 'Pendiente', 'No aplica', 'Otro'],
    colSpan: 'half',
    sectionTitle: 'Secuenciación',
    hidden: true,
  },
  {
    id: 'secuenciacion_fecha',
    label: 'Fecha de Secuenciación',
    type: 'date',
    page: 8,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
    hidden: true,
  },

  // Muestras Rechazadas (Boleta de Rechazo - Laboratorio Nacional de Salud)
  {
    id: 'muestra_rechazada',
    label: '¿Alguna muestra fue rechazada por el laboratorio?',
    type: 'radio',
    page: 8,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'full',
    sectionTitle: 'Muestras Rechazadas',
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
  },
  {
    id: 'muestra_rechazada_codigo',
    label: 'Código de boleta de rechazo',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Ej: 597/2026',
    conditional: { dependsOn: 'muestra_rechazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_rechazada_fecha',
    label: 'Fecha de rechazo',
    type: 'date',
    page: 8,
    required: false,
    conditional: { dependsOn: 'muestra_rechazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'muestra_rechazada_criterio',
    label: 'Criterio de rechazo',
    type: 'select',
    page: 8,
    required: false,
    options: [
      'Ficha epidemiológica o boleta sin muestra',
      'Muestras sin identificación',
      'Muestras derramadas',
      'Tubo o recipiente sin muestra',
      'Muestra con volumen insuficiente',
      'Condiciones de transporte inadecuadas',
      'Muestras inadecuadas para el análisis',
      'Recipiente o tubo inadecuado',
      'Muestras de otros eventos',
      'Otro',
    ],
    conditional: { dependsOn: 'muestra_rechazada', showWhen: 'SI' },
    colSpan: 'full',
  },
  {
    id: 'muestra_rechazada_criterio_otro',
    label: 'Especifique otro criterio',
    type: 'text',
    page: 8,
    required: false,
    placeholder: 'Describa el criterio de rechazo',
    conditional: { dependsOn: 'muestra_rechazada_criterio', showWhen: 'Otro' },
    colSpan: 'half',
  },
  {
    id: 'muestra_rechazada_tipo',
    label: 'Tipo de muestra rechazada',
    type: 'select',
    page: 8,
    required: false,
    options: ['Suero', 'Orina', 'Hisopado Nasofaríngeo', 'Otra'],
    conditional: { dependsOn: 'muestra_rechazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_rechazada_observaciones',
    label: 'Observaciones del rechazo',
    type: 'textarea',
    page: 8,
    required: false,
    placeholder: 'Detalles adicionales del rechazo',
    conditional: { dependsOn: 'muestra_rechazada', showWhen: 'SI' },
    colSpan: 'full',
    validation: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════
  // TAB 9: CLASIFICACIÓN Y DATOS IGSS
  // ═══════════════════════════════════════════════════
  {
    id: 'contactos_directos',
    label: 'No. de Contactos Directos',
    type: 'number',
    page: 9,
    required: false,
    placeholder: '0',
    helpText: 'Número de contactos directos identificados',
    colSpan: 'half',
    validation: { min: 0, max: 999 },
  },
  {
    id: 'clasificacion_caso',
    label: 'Clasificación del Caso',
    type: 'select',
    page: 9,
    required: true,
    options: [
      'SOSPECHOSO',
      'CONFIRMADO SARAMPIÓN',
      'NO CUMPLE DEFINICIÓN DE CASO',
    ],
    helpText: 'Clasificación del caso según protocolo MSPAS 2026',
    colSpan: 'half',
  },
  {
    id: 'criterio_confirmacion',
    label: 'Criterio de Confirmación',
    type: 'select',
    page: 9,
    required: false,
    options: ['Laboratorio', 'Nexo Epidemiológico', 'Clínico'],
    conditional: { dependsOn: 'clasificacion_caso', showWhen: ['CONFIRMADO SARAMPIÓN', 'CONFIRMADO RUBÉOLA'] },
    colSpan: 'half',
  },
  {
    id: 'nexo_numero_ficha',
    label: 'Número de Ficha / Laboratorio Confirmatorio de Sarampión',
    type: 'text',
    page: 9,
    required: true,
    placeholder: 'Número de ficha del caso confirmatorio',
    conditional: { dependsOn: 'criterio_confirmacion', showWhen: 'Nexo Epidemiológico' },
    colSpan: 'half',
    helpText: 'Estos datos serán validados con el Laboratorio Nacional de Salud',
  },
  {
    id: 'nexo_nombre_caso_confirmatorio',
    label: 'Nombre Completo del Caso Confirmatorio',
    type: 'text',
    page: 9,
    required: true,
    placeholder: 'Nombre completo del paciente del caso confirmatorio',
    conditional: { dependsOn: 'criterio_confirmacion', showWhen: 'Nexo Epidemiológico' },
    colSpan: 'half',
    helpText: 'Datos validados con Laboratorio Nacional de Salud (LNS)',
  },
  {
    id: 'criterio_descarte',
    label: 'Criterio para descartar',
    type: 'select',
    page: 9,
    required: false,
    options: [
      'Laboratorio',
      'Reacción por vacuna',
      'Clínico',
    ],
    helpText: 'Si corresponde: indicar el criterio por el cual se descarta el caso',
    colSpan: 'half',
  },
  {
    id: 'fuente_infeccion',
    label: 'Fuente de Infección',
    type: 'select',
    page: 9,
    required: false,
    options: [
      'Importado',
      'Relacionado con la importación',
      'Endémico',
      'Fuente desconocida',
    ],
    conditional: { dependsOn: 'clasificacion_caso', showWhen: ['CONFIRMADO SARAMPIÓN', 'CONFIRMADO RUBÉOLA'] },
    colSpan: 'half',
  },
  {
    id: 'pais_importacion',
    label: 'País de Importación',
    type: 'select',
    page: 9,
    required: false,
    searchable: true,
    options: [
      'GUATEMALA',
      // Centroamérica
      'MÉXICO', 'HONDURAS', 'EL SALVADOR', 'BELICE', 'NICARAGUA', 'COSTA RICA', 'PANAMÁ',
      // Caribe
      'REPÚBLICA DOMINICANA', 'HAITÍ', 'CUBA', 'JAMAICA', 'PUERTO RICO',
      // Sudamérica
      'COLOMBIA', 'VENEZUELA', 'BRASIL', 'ARGENTINA', 'PERÚ', 'CHILE', 'ECUADOR', 'BOLIVIA', 'URUGUAY', 'PARAGUAY',
      // Norteamérica
      'ESTADOS UNIDOS', 'CANADÁ',
      // Europa
      'ESPAÑA', 'FRANCIA', 'ITALIA', 'ALEMANIA', 'REINO UNIDO',
      // Asia
      'CHINA', 'INDIA', 'JAPÓN', 'COREA DEL SUR',
      // Otro
      'OTRO',
    ],
    conditional: { dependsOn: 'fuente_infeccion', showWhen: 'Importado' },
    colSpan: 'half',
  },
  {
    id: 'contacto_otro_caso',
    label: '¿Tuvo contacto con otro caso confirmado?',
    type: 'radio',
    page: 9,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'contacto_otro_caso_detalle',
    label: 'Detalle del contacto con otro caso',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Describa el contacto con otro caso',
    conditional: { dependsOn: 'contacto_otro_caso', showWhen: 'SI' },
    colSpan: 'full',
    validation: { maxLength: 300 },
  },
  {
    id: 'caso_analizado_por',
    label: 'Caso Analizado por',
    type: 'select',
    page: 9,
    required: false,
    options: ['CONAPI', 'DEGR', 'Comisión Nacional', 'Otros'],
    colSpan: 'half',
  },
  {
    id: 'caso_analizado_por_otro',
    label: 'Especifique quién analizó el caso',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'caso_analizado_por', showWhen: 'Otros' },
    colSpan: 'half',
    validation: { maxLength: 150 },
  },
  {
    id: 'fecha_clasificacion_final',
    label: 'Fecha de Clasificación Final',
    type: 'date',
    page: 9,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'responsable_clasificacion',
    label: 'Responsable de Clasificación',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Nombre del responsable de clasificación',
    colSpan: 'half',
  },

  // Condición Final
  {
    id: 'condicion_final_paciente',
    label: 'Condición Final del Paciente',
    type: 'select',
    page: 9,
    required: false,
    options: ['Recuperado', 'Con Secuelas', 'Fallecido', 'Desconocido'],
    colSpan: 'half',
    sectionTitle: 'Condición Final',
  },
  {
    id: 'fecha_defuncion',
    label: 'Fecha de Fallecimiento',
    type: 'date',
    page: 9,
    required: true,
    conditional: { dependsOn: 'condicion_final_paciente', showWhen: 'Fallecido' },
    colSpan: 'half',
    validation: { noFuture: true, yearMin: 2024, yearMax: 2027, flexibleParse: true },
  },
  {
    id: 'causa_muerte_certificado',
    label: 'Causa de Muerte en Certificado',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Causa de muerte según certificado de defunción',
    conditional: { dependsOn: 'condicion_final_paciente', showWhen: 'Fallecido' },
    colSpan: 'full',
    validation: { maxLength: 300 },
  },

  {
    id: 'observaciones',
    label: 'Observaciones',
    type: 'textarea',
    page: 9,
    required: false,
    placeholder: 'Observaciones adicionales del caso',
    colSpan: 'full',
    validation: { maxLength: 1000 },
  },

  // --- Datos IGSS ---
  {
    id: 'es_empleado_igss',
    label: '¿Es empleado del Seguro Social?',
    type: 'radio',
    page: 9,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
    sectionTitle: 'Datos IGSS',
  },
  {
    id: 'unidad_medica_trabaja',
    label: 'Unidad Médica en la que Trabaja',
    type: 'select',
    page: 9,
    required: false,
    options: unidadesMedicasNombres,
    searchable: true,
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'puesto_desempena',
    label: 'Puesto que Desempeña',
    type: 'select',
    page: 9,
    required: false,
    searchable: true,
    options: [
      'Médico/a',
      'Enfermero/a Profesional',
      'Auxiliar de Enfermería',
      'Técnico/a de Laboratorio',
      'Técnico/a en Salud',
      'Estadígrafo/a',
      'Secretario/a',
      'Personal Administrativo',
      'Personal de Mantenimiento',
      'Personal de Seguridad',
      'Personal de Limpieza',
      'Otro',
    ],
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'subgerencia_igss',
    label: 'Subgerencia',
    type: 'select',
    page: 9,
    required: false,
    options: getSubgerencias(),
    searchable: true,
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'full',
    sectionTitle: 'Ubicación Organizacional IGSS',
  },
  {
    id: 'subgerencia_igss_otra',
    label: 'Especifique Subgerencia',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Nombre de la subgerencia',
    conditional: { dependsOn: 'subgerencia_igss', showWhen: 'OTRA' },
    colSpan: 'full',
  },
  {
    id: 'direccion_igss',
    label: 'Dirección',
    type: 'select',
    page: 9,
    required: false,
    options: [],
    searchable: true,
    cascadeFrom: 'subgerencia_igss',
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'direccion_igss_otra',
    label: 'Especifique Dirección',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Nombre de la dirección',
    conditional: { dependsOn: 'direccion_igss', showWhen: 'OTRA' },
    colSpan: 'half',
  },
  {
    id: 'departamento_igss',
    label: 'Departamento IGSS',
    type: 'select',
    page: 9,
    required: false,
    options: [],
    searchable: true,
    cascadeFrom: 'subgerencia_igss_depto',
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'departamento_igss_otro',
    label: 'Especifique Departamento',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Nombre del departamento',
    conditional: { dependsOn: 'departamento_igss', showWhen: 'OTRO' },
    colSpan: 'half',
  },
  {
    id: 'seccion_igss',
    label: 'Sección',
    type: 'select',
    page: 9,
    required: false,
    options: [],
    searchable: true,
    cascadeFrom: 'departamento_igss_seccion',
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'seccion_igss_otra',
    label: 'Especifique Sección',
    type: 'text',
    page: 9,
    required: false,
    placeholder: 'Nombre de la sección',
    conditional: { dependsOn: 'seccion_igss', showWhen: 'OTRA' },
    colSpan: 'half',
  },
]

// Campos que se agregan automáticamente al envío
export const autoFields = [
  'registro_id',
  'timestamp_envio',
  'nombre_apellido', // Computed: nombres + apellidos
]

// Obtener el total de páginas
export const getTotalPages = () => {
  return Math.max(...formFields.map(f => f.page))
}

// Obtener campos de una página específica
export const getFieldsByPage = (page) => {
  return formFields.filter(f => f.page === page)
}

// Cache bust v2
