/**
 * Schema del formulario de Vigilancia Epidemiológica - Sarampión/Rubéola
 * Compatible con MSPAS EPIWEB (Tabs 1-5) + campos IGSS adicionales
 *
 * Estructura: 7 tabs
 *   1. Datos Generales (Unidad Notificadora)
 *   2. Datos del Paciente
 *   3. Embarazo (condicional sexo=F)
 *   4. Información Clínica (Conocimiento + Exposición + Signos + Vacunación + Hospitalización)
 *   5. Factores de Riesgo
 *   6. Laboratorio
 *   7. Contactos y Datos IGSS
 */

import { unidadesMedicasNombres } from './unidadesMedicas.js'
import { etniasOptions } from './mspasEtnias.js'
import { ocupacionesOptions } from './mspasOcupaciones.js'
import { escolaridadOptions } from './mspasEscolaridad.js'
import { departamentos, getMunicipios } from './mspasMunicipios.js'
import { getPoblados } from './mspasPoblados.js'

export const formTitle = 'Ficha de Investigación Epidemiológica'
export const formSubtitle = 'Sarampión / Rubéola — IGSS Epidemiología'
export const institutionName = 'Instituto Guatemalteco de Seguridad Social'

export const pageLabels = {
  1: 'Datos Generales',
  2: 'Datos del Paciente',
  3: 'Embarazo',
  4: 'Información Clínica',
  5: 'Factores de Riesgo',
  6: 'Laboratorio',
  7: 'Contactos y Datos IGSS',
}

export const diagnosticosMap = {
  'B05 - Sarampión': 'B05',
  'B050 - Sarampión complicado por encefalitis': 'B050',
  'B051 - Sarampión complicado por meningitis': 'B051',
  'B052 - Sarampión complicado por una neumonía': 'B052',
  'B053 - Sarampión complicado por otitis media': 'B053',
  'B054 - Sarampión con complicaciones intestinales': 'B054',
  'B055 - Sarampión confirmado por laboratorio': 'B055',
  'B056 - Sarampión confirmado por nexo epidemiológico': 'B056',
  'B057 - Sarampión confirmado clínicamente': 'B057',
  'B058 - Sarampión con otras complicaciones': 'B058',
  'B059 - Sospechoso de Sarampión': 'B059',
}

export const departamentosGuatemala = departamentos

// Re-export for cascading selects
export { getMunicipios, getPoblados }

export const formFields = [
  // ═══════════════════════════════════════════════════
  // TAB 1: DATOS GENERALES — Unidad Notificadora
  // ═══════════════════════════════════════════════════
  {
    id: 'diagnostico_registrado',
    label: 'Diagnóstico Registrado',
    type: 'select',
    page: 1,
    required: true,
    options: Object.keys(diagnosticosMap),
    autoMap: 'codigo_cie10',
    helpText: 'Seleccione el diagnóstico CIE-10 registrado en la consulta',
    colSpan: 'half',
  },
  {
    id: 'codigo_cie10',
    label: 'Código CIE-10',
    type: 'text',
    page: 1,
    required: false,
    placeholder: 'Se asigna automáticamente',
    colSpan: 'half',
    readOnly: true,
    autoFrom: 'diagnostico_registrado',
    validation: { maxLength: 10 },
  },
  {
    id: 'unidad_medica',
    label: 'Unidad Médica que Reporta',
    type: 'select',
    page: 1,
    required: true,
    options: unidadesMedicasNombres,
    searchable: true,
    helpText: 'Unidad médica del IGSS que reporta el caso',
    colSpan: 'half',
  },
  {
    id: 'unidad_medica_otra',
    label: 'Especifique la unidad médica',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Nombre de la unidad médica',
    conditional: { dependsOn: 'unidad_medica', showWhen: 'OTRA' },
    colSpan: 'half',
  },
  {
    id: 'fecha_notificacion',
    label: 'Fecha de Notificación',
    type: 'date',
    page: 1,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fecha_registro_diagnostico',
    label: 'Fecha de Registro de Diagnóstico',
    type: 'date',
    page: 1,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'semana_epidemiologica',
    label: 'Semana Epidemiológica',
    type: 'number',
    page: 1,
    required: true,
    placeholder: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 1, max: 53 },
    autoCalculate: 'epiWeek',
    dependsOnDate: 'fecha_notificacion',
    helpText: 'Se calcula automáticamente según la fecha de notificación (sistema MMWR/CDC)',
    readOnly: true,
  },
  {
    id: 'servicio_reporta',
    label: 'Servicio que Reporta',
    type: 'select',
    page: 1,
    required: true,
    options: ['EMERGENCIA', 'CONSULTA EXTERNA', 'ENCAMAMIENTO', 'OTRO'],
    colSpan: 'half',
  },
  {
    id: 'nom_responsable',
    label: 'Responsable de Notificación',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Nombre del responsable',
    colSpan: 'half',
    sectionTitle: 'Responsable',
  },
  {
    id: 'cargo_responsable',
    label: 'Cargo',
    type: 'text',
    page: 1,
    required: true,
    placeholder: 'Cargo del responsable',
    colSpan: 'half',
  },
  {
    id: 'telefono_responsable',
    label: 'Teléfono',
    type: 'phone',
    page: 1,
    required: false,
    placeholder: 'Teléfono del responsable',
    colSpan: 'half',
  },
  {
    id: 'envio_ficha',
    label: '¿Enviaron Ficha Epidemiológica?',
    type: 'radio',
    page: 1,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },

  // ═══════════════════════════════════════════════════
  // TAB 2: DATOS DEL PACIENTE
  // ═══════════════════════════════════════════════════
  {
    id: 'afiliacion',
    label: 'Número de Afiliación',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Número de afiliación del paciente',
    helpText: 'Número de afiliación IGSS o número de registro',
    colSpan: 'half',
    validation: { minLength: 3, maxLength: 20 },
  },
  {
    id: 'nombres',
    label: 'Nombres',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Nombres del paciente',
    colSpan: 'half',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    id: 'apellidos',
    label: 'Apellidos',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Apellidos del paciente',
    colSpan: 'half',
    validation: { minLength: 2, maxLength: 100 },
  },
  {
    id: 'sexo',
    label: 'Sexo',
    type: 'radio',
    page: 2,
    required: true,
    options: ['M', 'F'],
    optionLabels: { M: 'Masculino', F: 'Femenino' },
    colSpan: 'half',
  },
  {
    id: 'fecha_nacimiento',
    label: 'Fecha de Nacimiento',
    type: 'date',
    page: 2,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
    sectionTitle: 'Edad',
  },
  {
    id: 'edad_anios',
    label: 'Edad en Años',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    colSpan: 'half',
    validation: { min: 0, max: 120 },
    helpText: 'Se calcula automáticamente desde fecha de nacimiento',
    readOnly: true,
  },
  {
    id: 'edad_meses',
    label: 'Edad en Meses',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    helpText: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 0, max: 11 },
    readOnly: true,
  },
  {
    id: 'edad_dias',
    label: 'Edad en Días',
    type: 'number',
    page: 2,
    required: false,
    placeholder: '0',
    helpText: 'Se calcula automáticamente',
    colSpan: 'half',
    validation: { min: 0, max: 31 },
    readOnly: true,
  },
  {
    id: 'pueblo_etnia',
    label: 'Pueblo / Etnia',
    type: 'select',
    page: 2,
    required: true,
    options: etniasOptions,
    colSpan: 'half',
    sectionTitle: 'Datos Sociodemográficos',
  },
  {
    id: 'ocupacion',
    label: 'Ocupación',
    type: 'select',
    page: 2,
    required: true,
    options: ocupacionesOptions,
    searchable: true,
    colSpan: 'half',
  },
  {
    id: 'escolaridad',
    label: 'Escolaridad',
    type: 'select',
    page: 2,
    required: true,
    options: escolaridadOptions,
    colSpan: 'half',
  },
  {
    id: 'departamento_residencia',
    label: 'Departamento de Residencia',
    type: 'select',
    page: 2,
    required: true,
    options: departamentosGuatemala,
    colSpan: 'half',
    sectionTitle: 'Residencia',
  },
  {
    id: 'municipio_residencia',
    label: 'Municipio de Residencia',
    type: 'select',
    page: 2,
    required: true,
    options: [], // Se llena dinámicamente según departamento
    searchable: true,
    cascadeFrom: 'departamento_residencia',
    colSpan: 'half',
  },
  {
    id: 'poblado',
    label: 'Poblado / Localidad',
    type: 'select',
    page: 2,
    required: false,
    options: [], // Se llena dinámicamente según departamento + municipio
    searchable: true,
    cascadeFrom: 'municipio_residencia',
    colSpan: 'half',
  },
  {
    id: 'direccion_exacta',
    label: 'Dirección',
    type: 'textarea',
    page: 2,
    required: false,
    placeholder: 'Dirección del paciente',
    colSpan: 'full',
    validation: { maxLength: 300 },
  },
  {
    id: 'nombre_encargado',
    label: 'Nombre de la madre, padre o encargado',
    type: 'text',
    page: 2,
    required: true,
    placeholder: 'Nombre del encargado(a) del paciente',
    colSpan: 'full',
    sectionTitle: 'Encargado',
  },

  // ═══════════════════════════════════════════════════
  // TAB 3: EMBARAZO (condicional sexo=F)
  // ═══════════════════════════════════════════════════
  {
    id: 'esta_embarazada',
    label: '¿Está Embarazada?',
    type: 'radio',
    page: 3,
    required: true,
    options: ['SI', 'NO', 'N/A'],
    conditional: { dependsOn: 'sexo', showWhen: 'F' },
    colSpan: 'full',
  },
  {
    id: 'lactando',
    label: '¿Está Lactando?',
    type: 'radio',
    page: 3,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'sexo', showWhen: 'F' },
    colSpan: 'full',
  },
  {
    id: 'semanas_embarazo',
    label: 'Semanas de Embarazo',
    type: 'number',
    page: 3,
    required: true,
    placeholder: 'Semanas',
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { min: 1, max: 42 },
  },
  {
    id: 'fecha_probable_parto',
    label: 'Fecha Probable de Parto',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'vacuna_embarazada',
    label: 'Vacuna (en embarazada)',
    type: 'select',
    page: 3,
    required: false,
    options: ['SI', 'NO', 'N/S', 'N/A'],
    conditional: { dependsOn: 'esta_embarazada', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'fecha_vacunacion_embarazada',
    label: 'Fecha de Vacunación',
    type: 'date',
    page: 3,
    required: false,
    conditional: { dependsOn: 'vacuna_embarazada', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },

  // ═══════════════════════════════════════════════════
  // TAB 4: INFORMACIÓN CLÍNICA
  // ═══════════════════════════════════════════════════

  // --- Conocimiento del Caso ---
  {
    id: 'fecha_inicio_sintomas',
    label: 'Fecha Inicio Síntomas',
    type: 'date',
    page: 4,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
    sectionTitle: 'Conocimiento del Caso',
  },
  {
    id: 'fecha_captacion',
    label: 'Fecha de Captación',
    type: 'date',
    page: 4,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fuente_notificacion',
    label: 'Fuente de Notificación',
    type: 'select',
    page: 4,
    required: true,
    options: [
      'Pública',
      'Privada',
      'Laboratorio',
      'Comunidad',
      'Búsqueda Activa',
      'Defunción',
      'Otra',
    ],
    colSpan: 'half',
  },
  {
    id: 'fuente_notificacion_otra',
    label: 'Otra fuente de notificación',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Especifique otra fuente',
    conditional: { dependsOn: 'fuente_notificacion', showWhen: 'Otra' },
    colSpan: 'half',
  },
  {
    id: 'fecha_visita_domiciliaria',
    label: 'Fecha Visita Domiciliaria',
    type: 'date',
    page: 4,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fecha_inicio_investigacion',
    label: 'Fecha Inicio Investigación',
    type: 'date',
    page: 4,
    required: false,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'busqueda_activa',
    label: 'Búsqueda Activa',
    type: 'select',
    page: 4,
    required: false,
    options: [
      'Retrospectiva en el servicio',
      'Comunidad',
      'Otras',
    ],
    colSpan: 'half',
  },
  {
    id: 'busqueda_activa_otra',
    label: 'Otra búsqueda activa',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'busqueda_activa', showWhen: 'Otras' },
    colSpan: 'half',
  },

  // --- Circunstancias de Exposición ---
  {
    id: 'fecha_inicio_erupcion',
    label: 'Fecha Inicio Erupción',
    type: 'date',
    page: 4,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
    sectionTitle: 'Circunstancias de Exposición',
  },
  {
    id: 'sitio_inicio_erupcion',
    label: 'Sitio de Inicio de Erupción',
    type: 'select',
    page: 4,
    required: true,
    options: [
      'Retroauricular',
      'Cara',
      'Cuello',
      'Tórax',
      'Otro',
    ],
    colSpan: 'half',
  },
  {
    id: 'sitio_inicio_erupcion_otro',
    label: 'Otro sitio de erupción',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'sitio_inicio_erupcion', showWhen: 'Otro' },
    colSpan: 'half',
  },
  {
    id: 'fecha_inicio_fiebre',
    label: 'Fecha Inicio Fiebre',
    type: 'date',
    page: 4,
    required: true,
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'temperatura_celsius',
    label: 'Temperatura °C',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Ej: 38.5',
    colSpan: 'half',
    validation: { pattern: '^\\d{2}([.,]\\d{1,2})?$' },
    helpText: 'Temperatura en grados Celsius (ej: 38.5 o 38,5)',
  },

  // --- Signos y Síntomas ---
  {
    id: 'signo_fiebre',
    label: 'Fiebre',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Signos y Síntomas',
  },
  {
    id: 'signo_exantema',
    label: 'Exantema',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_manchas_koplik',
    label: 'Manchas de Koplik',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_tos',
    label: 'Tos',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_conjuntivitis',
    label: 'Conjuntivitis',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_coriza',
    label: 'Coriza (catarro)',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_adenopatias',
    label: 'Adenopatías',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },
  {
    id: 'signo_artralgia',
    label: 'Artralgia o Artritis',
    type: 'radio',
    page: 4,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'half',
  },

  // --- Antecedentes de Vacunación ---
  {
    id: 'vacunado',
    label: 'Vacunado',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Antecedentes de Vacunación',
  },
  {
    id: 'fuente_info_vacuna',
    label: 'Fuente de Información',
    type: 'select',
    page: 4,
    required: true,
    options: [
      'En carné',
      'En SIGSA 5a',
      'En cuadernillos',
      'Verbal',
    ],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'tipo_vacuna',
    label: 'Tipo de Vacuna',
    type: 'select',
    page: 4,
    required: true,
    options: [
      'Antisarampinosa',
      'Antirubeólica',
      'SR Sarampión Rubéola',
      'SRP Sarampión Rubéola Paperas',
      'No recuerda',
    ],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'numero_dosis_spr',
    label: 'Número de Dosis',
    type: 'select',
    page: 4,
    required: true,
    options: ['1 dosis', '2 dosis', '3 dosis', 'Más de 3 dosis', 'No recuerda'],
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'fecha_ultima_dosis',
    label: 'Fecha Última Dosis',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'observaciones_vacuna',
    label: 'Observaciones de Vacunación',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Si se perdió el carné, anotar información verbal',
    conditional: { dependsOn: 'vacunado', showWhen: 'SI' },
    colSpan: 'full',
  },

  // --- Hospitalización y Defunción ---
  {
    id: 'hospitalizado',
    label: '¿Fue Hospitalizado?',
    type: 'radio',
    page: 4,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'half',
    sectionTitle: 'Hospitalización y Defunción',
  },
  {
    id: 'hosp_nombre',
    label: 'Nombre del Hospital',
    type: 'text',
    page: 4,
    required: true,
    placeholder: 'Nombre del hospital',
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'hosp_fecha',
    label: 'Fecha de Hospitalización',
    type: 'date',
    page: 4,
    required: true,
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'no_registro_medico',
    label: 'No. de Registro Médico',
    type: 'text',
    page: 4,
    required: true,
    placeholder: 'Número de registro médico',
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'condicion_egreso',
    label: 'Condición de Egreso',
    type: 'select',
    page: 4,
    required: false,
    options: ['MEJORADO', 'GRAVE', 'MUERTO'],
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'fecha_egreso',
    label: 'Fecha de Egreso',
    type: 'date',
    page: 4,
    required: false,
    conditional: { dependsOn: 'hospitalizado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fecha_defuncion',
    label: 'Fecha de Defunción',
    type: 'date',
    page: 4,
    required: true,
    conditional: { dependsOn: 'condicion_egreso', showWhen: 'MUERTO' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'medico_certifica_defuncion',
    label: 'Médico que Certifica Defunción',
    type: 'text',
    page: 4,
    required: false,
    placeholder: 'Nombre del médico',
    conditional: { dependsOn: 'condicion_egreso', showWhen: 'MUERTO' },
    colSpan: 'half',
  },
  {
    id: 'motivo_consulta',
    label: 'Motivo de Consulta / Observaciones Clínicas',
    type: 'textarea',
    page: 4,
    required: false,
    placeholder: 'Describa el motivo de consulta u observaciones',
    colSpan: 'full',
    validation: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════
  // TAB 5: FACTORES DE RIESGO
  // ═══════════════════════════════════════════════════
  {
    id: 'contacto_sospechoso_7_23',
    label: 'Tuvo contacto con otro sospechoso de 7-23 días antes del inicio de la erupción',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },
  {
    id: 'caso_sospechoso_comunidad_3m',
    label: 'Hubo algún caso sospechoso en la comunidad o municipio antes de este caso, en los últimos 3 meses',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },
  {
    id: 'viajo_7_23_previo',
    label: 'Viajó durante los 7-23 días previos al inicio de la erupción',
    type: 'radio',
    page: 5,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },
  {
    id: 'destino_viaje',
    label: '¿A dónde viajó?',
    type: 'text',
    page: 5,
    required: false,
    placeholder: 'Indique el destino del viaje',
    conditional: { dependsOn: 'viajo_7_23_previo', showWhen: 'SI' },
    colSpan: 'full',
  },
  {
    id: 'contacto_enfermo_catarro',
    label: '¿Tuvo contacto con algún enfermo con catarro o erupción?',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },
  {
    id: 'contacto_embarazada',
    label: '¿Tuvo contacto con una embarazada?',
    type: 'radio',
    page: 5,
    required: false,
    options: ['SI', 'NO'],
    colSpan: 'full',
  },

  // ═══════════════════════════════════════════════════
  // TAB 6: LABORATORIO
  // ═══════════════════════════════════════════════════
  {
    id: 'recolecto_muestra',
    label: 'Recolectó Muestra',
    type: 'radio',
    page: 6,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
    sectionTitle: 'Muestras de Laboratorio',
  },
  {
    id: 'muestra_suero',
    label: 'Suero',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_suero_fecha',
    label: 'Fecha Recolección Suero',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'muestra_suero', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'muestra_hisopado',
    label: 'Hisopado Nasofaríngeo',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_hisopado_fecha',
    label: 'Fecha Recolección Hisopado',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'muestra_hisopado', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'muestra_orina',
    label: 'Orina',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_orina_fecha',
    label: 'Fecha Recolección Orina',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'muestra_orina', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'muestra_otra',
    label: 'Otra Muestra',
    type: 'radio',
    page: 6,
    required: false,
    options: ['SI', 'NO'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_otra_descripcion',
    label: 'Descripción Otra Muestra',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Tipo de muestra',
    conditional: { dependsOn: 'muestra_otra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'muestra_otra_fecha',
    label: 'Fecha Recolección Otra Muestra',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'muestra_otra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'antigeno_prueba',
    label: 'Antígeno',
    type: 'select',
    page: 6,
    required: false,
    options: ['Sarampión', 'Rubéola', 'Dengue', 'Otros'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    sectionTitle: 'Resultados de Laboratorio',
  },
  {
    id: 'antigeno_otro',
    label: 'Otro Antígeno',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Especifique',
    conditional: { dependsOn: 'antigeno_prueba', showWhen: 'Otros' },
    colSpan: 'half',
  },
  {
    id: 'resultado_prueba',
    label: 'Resultado de Prueba',
    type: 'select',
    page: 6,
    required: false,
    options: ['Negativo', 'Positivo', 'Muestra Inadecuada', 'Indeterminada'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'fecha_recepcion_laboratorio',
    label: 'Fecha Recepción en Laboratorio',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  {
    id: 'fecha_resultado_laboratorio',
    label: 'Fecha de Resultado',
    type: 'date',
    page: 6,
    required: false,
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    validation: { noFuture: true },
  },
  // Resultados detallados (mantener compatibilidad)
  {
    id: 'resultado_igg_cualitativo',
    label: 'Resultado IgG Cualitativo',
    type: 'select',
    page: 6,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
    sectionTitle: 'Resultados Detallados (IGSS)',
  },
  {
    id: 'resultado_igg_numerico',
    label: 'Resultado IgG Numérico',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Valor numérico',
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'resultado_igm_cualitativo',
    label: 'Resultado IgM Cualitativo',
    type: 'select',
    page: 6,
    required: false,
    options: ['REACTIVO', 'NO REACTIVO', 'INDETERMINADO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'resultado_igm_numerico',
    label: 'Resultado IgM Numérico',
    type: 'text',
    page: 6,
    required: false,
    placeholder: 'Valor numérico',
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'resultado_pcr_orina',
    label: 'Resultado RT-PCR Orina',
    type: 'select',
    page: 6,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'resultado_pcr_hisopado',
    label: 'Resultado RT-PCR Hisopado',
    type: 'select',
    page: 6,
    required: false,
    options: ['POSITIVO', 'NEGATIVO', 'PENDIENTE', 'N/A'],
    conditional: { dependsOn: 'recolecto_muestra', showWhen: 'SI' },
    colSpan: 'half',
  },

  // ═══════════════════════════════════════════════════
  // TAB 7: CONTACTOS Y DATOS IGSS
  // ═══════════════════════════════════════════════════
  {
    id: 'contactos_directos',
    label: 'No. de Contactos Directos',
    type: 'number',
    page: 7,
    required: false,
    placeholder: '0',
    helpText: 'Número de contactos directos identificados',
    colSpan: 'half',
    validation: { min: 0, max: 999 },
  },
  {
    id: 'clasificacion_caso',
    label: 'Clasificación del Caso',
    type: 'select',
    page: 7,
    required: true,
    options: [
      'SOSPECHOSO',
      'CONFIRMADO',
      'DESCARTADO',
      'SUSPENDIDO',
      'CLÍNICO',
      'FALSO',
      'ERROR DIAGNÓSTICO',
    ],
    helpText: 'Clasificación del caso según protocolo',
    colSpan: 'half',
  },
  {
    id: 'observaciones',
    label: 'Observaciones',
    type: 'textarea',
    page: 7,
    required: false,
    placeholder: 'Observaciones adicionales del caso',
    colSpan: 'full',
    validation: { maxLength: 1000 },
  },
  {
    id: 'es_empleado_igss',
    label: '¿Es empleado del Seguro Social?',
    type: 'radio',
    page: 7,
    required: true,
    options: ['SI', 'NO'],
    colSpan: 'full',
    sectionTitle: 'Datos IGSS',
  },
  {
    id: 'unidad_medica_trabaja',
    label: 'Unidad Médica en la que Trabaja',
    type: 'select',
    page: 7,
    required: false,
    options: unidadesMedicasNombres,
    searchable: true,
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
  {
    id: 'puesto_desempena',
    label: 'Puesto que Desempeña',
    type: 'text',
    page: 7,
    required: false,
    placeholder: 'Puesto o cargo del empleado',
    conditional: { dependsOn: 'es_empleado_igss', showWhen: 'SI' },
    colSpan: 'half',
  },
]

// Campos que se agregan automáticamente al envío
export const autoFields = [
  'registro_id',
  'timestamp_envio',
  'nombre_apellido', // Computed: nombres + apellidos
]

// Obtener el total de páginas
export const getTotalPages = () => {
  return Math.max(...formFields.map(f => f.page))
}

// Obtener campos de una página específica
export const getFieldsByPage = (page) => {
  return formFields.filter(f => f.page === page)
}
