/**
 * Opciones de ocupación del sistema MSPAS EPIWEB
 * Clasificación CIUO-08 adaptada para Guatemala
 * Fuente: cbox_ocupacion en sarampion_ingresar.php
 * Total: 441 opciones
 */
export const ocupacionesOptions = [
  'N/A',
  'Ama de casa',
  'Servicios Domésticos',
  'Abogados',
  'Acarreadores de agua y recolectores de leña',
  'Acompañantes y ayudantes de cámara',
  'Actores',
  'Administradores de sistemas',
  'Agentes de administración tributaria',
  'Agentes de aduana e inspectores de fronteras',
  'Agentes de bolsa, cambio y otros servicios financieros',
  'Agentes de compras',
  'Agentes de compras y consignatarios',
  'Agentes de empleo y contratistas de mano de obra',
  'Agentes de la administración pública para la aplicacion de la ley y afines',
  'Agentes de seguros',
  'Agentes de servicios comerciales no clasificados bajo otros epígrafes',
  'Agentes de servicios de expedición de licencias y permisos',
  'Agentes de servicios de seguridad social',
  'Agentes inmobiliarios',
  'Agricultores y trabajadores calificados de cultivos extensivos',
  'Agricultores y trabajadores calificados de cultivos mixtos',
  'Agricultores y trabajadores calificados de huertas, invernaderos, viveros y jardines',
  'Agricultores y trabajadores calificados de plantaciones de árboles y arbustos',
  'Agrónomos y afines',
  'Albañiles',
  'Alfareros y afines (barro, arcilla y abrasivos)',
  'Analistas de gestión y organización',
  'Analistas de sistemas',
  'Analistas financieros',
  'Aparejadores y empalmadores de cables',
  'Apelambradores, pellejeros y curtidores',
  'Apicultores y sericultores y trabajadores calificados de la apicultura y la sericultura',
  'Archivistas y curadores de museos',
  'Arquitectos',
  'Arquitectos paisajistas',
  'Artesanos de los tejidos, el cuero y materiales similares',
  'Artesanos en madera, cestería y materiales similares',
  'Artesanos no clasificados bajo otros epígrafes',
  'Artistas creativos e interpretativos no clasificados bajo otros epígrafes',
  'Artistas de artes plásticas',
  'Asesores financieros y en inversiones',
  'Asistentes de venta de tiendas y almacenes',
  'Astrólogos, adivinadores y afines',
  'Atletas y deportistas',
  'Audiólogos y logopedas',
  'Autores y otros escritores',
  'Auxiliares de maestros',
  'Auxiliares de servicio de abordo',
  'Auxiliares laicos de las religiones',
  'Avicultores y trabajadores calificados de la avicultura',
  'Ayudantes de ambulancias',
  'Ayudantes de cocina',
  'Bailarines y coreógrafos',
  'Barnizadores y afines',
  'Barrenderos y afines',
  'Bibliotecarios, documentalistas y afines',
  'Biólogos, botánicos, zoologos y afines',
  'Bomberos',
  'Buzos',
  'Cajeros de bancos y afines',
  'Cajeros y expendedores de billetes',
  'Cajistas, tipógrafos y afines',
  'Camareros de barra',
  'Camareros de mesas',
  'Capitanes, oficiales de cubierta y prácticos',
  'Carniceros, pescaderos y afines',
  'Carpinteros de armar y de obra blanca',
  'Cartógrafos y agrimensores',
  'Catadores y clasificadores de alimentos y bebidas',
  'Cazadores y tramperos',
  'Chapistas y caldereros',
  'Chefs',
  'Clasificadores de desechos',
  'Clasificadores y probadores de productos (excluyendo alimentos y bebidas)',
  'Cobradores y afines',
  'Cocineros',
  'Cocineros de comidas rápidas',
  'Codificadores de datos, correctores de pruebas de imprenta y afines',
  'Comerciantes de tiendas',
  'Conductores de autobuses y tranvías',
  'Conductores de automóviles, taxis y camionetas',
  'Conductores de camiones pesados',
  'Conductores de motocicletas',
  'Conductores de vehículos accionados a pedal o a brazo',
  'Conductores de vehículos y máquinas de tracción animal',
  'Conserjes',
  'Constructores de casas',
  'Contables',
  'Controladores de instalaciones de procesamiento de productos químicos',
  'Controladores de procesos de producción de metales',
  'Controladores de tráfico aéreo',
  'Costureros, bordadores y afines',
  'Criadores de ganado',
  'Criadores y trabajadores pecuarios calificados de la cría de animales no clasificados bajo otros epígrafes',
  'Cristaleros',
  'Cuidadores de animales',
  'Cuidadores de niños',
  'Declarantes o gestores de aduana',
  'Delineantes y dibujantes técnicos',
  'Demostradores de tiendas',
  'Dentistas',
  'Dentistas auxiliares y ayudantes de odontología',
  'Desarrolladores de software',
  'Desarrolladores Web y multimedia',
  'Desarrolladores y analistas de software y multimedia y analistas no clasificados bajo otros epígrafes',
  'Dietistas y nutricionistas',
  'Dinamiteros y pegadores',
  'Directores de administración y servicios no clasificados bajo epígrafes',
  'Directores de cine, de teatro y afines',
  'Directores de empresas de abastecimiento, distribución y afines',
  'Directores de empresas de construcción',
  'Directores de explotaciones de minería',
  'Directores de industrias manufactureras',
  'Directores de investigación y desarrollo',
  'Directores de políticas planeación',
  'Directores de producción agropecuaria y silvicultura',
  'Directores de producción de piscicultura y pesca',
  'Directores de publicidad y relaciones públicas',
  'Directores de recursos humanos',
  'Directores de servicios de bienestar social',
  'Directores de servicios de cuidado de las personas de edad',
  'Directores de servicios de cuidados infantiles',
  'Directores de servicios de educación',
  'Directores de servicios de salud',
  'Directores de servicios de tecnología de la información y las comunicaciones',
  'Directores de ventas y comercialización',
  'Directores financieros',
  'Directores generales y gerentes generales',
  'Directores y Gerentes de servicios profecionales no clasificados bajo otros epígrafes',
  'Dirigentes de organizaciones que presentan un interés especial',
  'Diseñadores de productos y de prendas',
  'Diseñadores gráficos y multimedia',
  'Diseñadores y administradores de bases de datos',
  'Diseñadores y decoradores de interior',
  'Ebanistas y afines',
  'Economistas',
  'Ecónomos y mayordomos domésticos',
  'Educadores para necesidades especiales',
  'Electricistas de obras y afines',
  'Electrotécnicos',
  'Empacadores manuales',
  'Empleados de agencias de viajes',
  'Empleados de archivos',
  'Empleados de bibliotecas',
  'Empleados de centros de llamadas',
  'Empleados de contabilidad y cálculo de costos',
  'Empleados de control de abastecimientos e inventario',
  'Empleados de servicios de apoyo a la producción',
  'Empleados de servicios de correos',
  'Empleados de servicios de información al cliente no clasificados bajo otros epígrafes',
  'Empleados de servicios de transporte',
  'Empleados de servicios estadísticos, financieros y de seguros',
  'Empleados de ventanillas de informaciones',
  'Empleados del servicio de personal',
  'Empleados encargados de las nóminas',
  'Ensambladores de equipos eléctricos y electrónicos',
  'Ensambladores de maquinaria mecánica',
  'Ensambladores no clasificados bajo otros epígrafes',
  'Encuadernadores y afines',
  'Entrenadores, instructores y árbitros de actividades deportivas',
  'Entrevistadores de encuestas y de investigaciones de mercados',
  'Escribientes públicos y afines',
  'Especialistas en bases de datos y en redes de computadores no clasificados bajo otros epígrafes',
  'Especialistas en formación del personal',
  'Especialistas en métodos pedagógicos',
  'Especialistas en políticas de administración',
  'Especialistas en políticas y servicios de personal y afines',
  'Especialistas en tratamientos de belleza y afines',
  'Expendedores de gasolineras',
  'Fabricantes y afinadores de instrumentos musicales',
  'Farmacéuticos',
  'Filósofos, historiadores y especialistas en ciencias políticas',
  'Físicos y astrónomos',
  'Físicos, químicos y afines',
  'Fisioterapeutas',
  'Fontaneros e instaladores de tuberías',
  'Fotógrafos',
  'Fumigadores y otros controladores de plagas y malas hierbas',
  'Geólogos y geofísicos',
  'Gerentes de centros deportivos, de esparcimiento y culturales',
  'Gerentes de comercios al por mayor y al por menor',
  'Gerentes de hoteles',
  'Gerentes de restaurantes',
  'Gerentes de servicios no clasificados bajo otros epígrafes',
  'Gerentes de sucursales de bancos, de servicios financieros y de seguros',
  'Grabadores de datos',
  'Guardianes de prisión',
  'Guardias de protección',
  'Guardafrenos, guardagujas y agentes de maniobras',
  'Guías de turismo',
  'Herramentistas y afines',
  'Herreros y forjadores',
  'Impresores',
  'Ingenieros civiles',
  'Ingenieros de minas, metalúrgicos y afines',
  'Ingenieros electricistas',
  'Ingenieros electrónicos',
  'Ingenieros en telecomunicaciones',
  'Ingenieros industriales y de producción',
  'Ingenieros mecánicos',
  'Ingenieros medioambientales',
  'Ingenieros no clasificados bajo otros epígrafes',
  'Ingenieros químicos',
  'Inspectores de la salud laboral, medioambiental y afines',
  'Inspectores de policía y detectives',
  'Instaladores de material aislante y de insonorización',
  'Instaladores y reparadores de líneas eléctricas',
  'Instaladores y reparadores en tecnología de la información y las comunicaciones',
  'Instructores de autoescuela',
  'Instructores de educación física y actividades recreativas',
  'Instructores en tecnología de la información',
  'Jefes de pequeñas poblaciones',
  'Joyeros, orfebres y plateros',
  'Jueces',
  'Lavadores de vehículos',
  'Lavadores de ventanas',
  'Lavanderos y planchadores manuales',
  'Limpiadores de fachadas y deshollinadores',
  'Limpiadores y asistentes de oficinas, hoteles y otros establecimientos',
  'Limpiadores y asistentes domésticos',
  'Locutores de radio, televisión y otros medios de comunicación',
  'Maestros de enseñanza primaria',
  'Maestros preescolares',
  'Mamposteros, tronzadores, labrantes y grabadores de piedra',
  'Maquinistas de locomotoras',
  'Marineros de cubierta y afines',
  'Matemáticas, actuarios y estadíticos',
  'Mecánicos y ajustadores electricistas',
  'Mecánicos y reparadores de instrumentos de precisión',
  'Mecánicos y reparadores de máquinas agrícolas e industriales',
  'Mecánicos y reparadores de motores de avión',
  'Mecánicos y reparadores de vehículos de motor',
  'Mecánicos y reparadores en electrónica',
  'Mecánicos-montadores de instalaciones de refrigeración y climatización',
  'Médicos especialistas',
  'Médicos generales',
  'Mensajeros, mandaderos, maleteros y repartidores',
  'Meteorólogos',
  'Miembros del poder legislativo',
  'Mineros y operadores de instalaciones mineras',
  'Modelos de moda, arte y publicidad',
  'Moldeadores y macheros',
  'Montadores de estructuras metálicas',
  'Músicos, cantantes y compositores',
  'Ocupaciones elementales no clasificadas bajo otros epígrafes',
  'Oficiales de las fuerzas armadas',
  'Oficiales de préstamos y créditos',
  'Oficiales maquinistas en navegación',
  'Oficiales y operarios de la construcción (obra gruesa) y afines no clasificados bajo otros epígrafes',
  'Oficiales, operarios y artesanos de artes mecánicas y de otros oficios no clasificados bajo otros epígrafes',
  'Oficinistas generales',
  'Operadores de autoelevadoras',
  'Operadores de grúas, aparatos elevadores y afines',
  'Operadores de incineradores, instalaciones de tratamiento de agua y afines',
  'Operadores de instalaciones de procesamiento de la madera',
  'Operadores de instalaciones de procesamiento de metales',
  'Operadores de instalaciones de procesamiento de minerales y rocas',
  'Operadores de instalaciones de producción de energía',
  'Operadores de instalaciones de refinación de petróleo y gas natural',
  'Operadores de instalaciones de vidriería y cerámica',
  'Operadores de instalaciones para la preparación de pasta para papel y papel',
  'Operadores de maquinaria agrícola y forestal móvil',
  'Operadores de máquinas de blanqueamiento, teñido y limpieza de tejidos',
  'Operadores de máquinas de coser',
  'Operadores de máquinas de embalaje, embotellamiento y etiquetado',
  'Operadores de máquinas de movimiento de tierras y afines',
  'Operadores de máquinas de preparación de fibras, hilado y devanado',
  'Operadores de máquinas de procesamiento de texto y Personal de apoyo administrativo no clasificado bajo otros epígrafes',
  'Operadores de máquinas de tratamiento de pieles y cueros',
  'Operadores de máquinas de vapor y calderas',
  'Operadores de máquinas lavarropas',
  'Operadores de máquinas para elaborar alimentos y productos afines',
  'Operadores de máquinas para fabricar cemento y otros productos minerales',
  'Operadores de máquinas para fabricar productos de caucho',
  'Operadores de máquinas para fabricar productos de material plástico',
  'Operadores de máquinas para fabricar productos de papel',
  'Operadores de máquinas para fabricar productos fotográficos',
  'Operadores de máquinas para fabricar productos textiles y artículos de piel y cuero no clasificados bajo otros epígrafes',
  'Operadores de máquinas para la fabricación de calzado y afines',
  'Operadores de máquinas pulidoras, galvanizadoras y recubridoras de metales',
  'Operadores de máquinas y de instalaciones fijas no clasificados bajo otros epígrafes',
  'Operadores de plantas y máquinas de productos químicos',
  'Operadores de telares y otras máquinas tejedoras',
  'Operarios de la conservación de frutas, legumbres, verduras y afines',
  'Operarios de la elaboración de productos lácteos',
  'Operarios del tratamiento de la madera',
  'Operarios en cemento armado, enfoscadores y afines',
  'Optometristas',
  'Organizadores de conferencias y eventos',
  'Otros miembros de las fuerzas armadas',
  'Otros profesionales de nivel medio en actividades culturales y artísticas',
  'Otros profesores de artes',
  'Otros profesores de idiomas',
  'Otros profesores de música',
  'Otro personal de limpieza',
  'Panaderos, pasteleros y confiteros',
  'Parqueteros y colocadores de suelos',
  'Patronistas y cortadores de tela y afines',
  'Peluqueros',
  'Peones de carga',
  'Peones de explotaciones agrícolas',
  'Peones de explotaciones de cultivos mixtos y ganaderos',
  'Peones de explotaciones ganaderas',
  'Peones de jardinería y horticultura',
  'Peones de la construcción de edificios',
  'Peones de la industria manufacturera no clasificados bajo otros epígrafes',
  'Peones de minas y canteras',
  'Peones de obras públicas y mantenimiento',
  'Peones de pesca y acuicultura',
  'Peones forestales',
  'Perforadores y sondistas de pozos y afines',
  'Periodistas',
  'Personal de los servicios de protección no clasificados bajo otros epígrafes',
  'Personal de pompas fúnebres y embalsamadores',
  'Personal directivo de la administración pública',
  'Personas que realizan trabajos varios',
  'Pescadores de agua dulce y en aguas costeras',
  'Pescadores de alta mar',
  'Pescadores, cazadores, tramperos y recolectores de subsistencia',
  'Pilotos de aviación y afines',
  'Pintores y empapeladores',
  'Policías',
  'Practicantes paramédicos',
  'Practicantes y asistentes médicos',
  'Preparadores y elaboradores de tabaco y sus productos',
  'Prestamistas',
  'Productores y trabajadores calificados de explotaciones agropecuarias mixtas cuya producción se destina al mercado',
  'Profecionales de la protección medioambiental',
  'Profesionales de enfermería',
  'Profesionales de la enseñanza no clasificados bajo otros epígrafes',
  'Profesionales de la publicidad y la comercialización',
  'Profesionales de la salud no clasificados bajo otros epígrafes',
  'Profesionales de la salud y la higiene laboral y ambiental',
  'Profesionales de medicina tradicional y alternativa',
  'Profesionales de nivel medio de enfermería',
  'Profesionales de nivel medio de medicina tradicional y alternativa',
  'Profesionales de nivel medio de partería',
  'Profesionales de nivel medio de servicios estadísticos, matemáticos y afines',
  'Profesionales de nivel medio del derecho y servicios legales y afines',
  'Profesionales de partería',
  'Profesionales de relaciones públicas',
  'Profesionales de ventas de tecnología de la información y las comunicaciones',
  'Profesionales de ventas técnicas y médicas (excluyendo la TIC)',
  'Profesionales del trabajo social',
  'Profesionales en derecho no clasificados bajo otros epígrafes',
  'Profesionales en redes de computadores',
  'Profesionales de la salud de nivel medio no clasificados bajo otros epígrafes',
  'Profesionales religiosos',
  'Profesores de enseñanza secundaria',
  'Profesores de formación profesional',
  'Profesores de universidades y de la enseñanza superior',
  'Programadores de aplicaciones',
  'Psicólogos',
  'Pulidores de metales y afiladores de herramientas',
  'Químicos',
  'Recepcionistas (general)',
  'Recepcionistas de hoteles',
  'Receptores de apuestas y afines',
  'Recolectores de basura y material reciclable',
  'Recolectores de dinero en aparatos de venta automática y lectores de medidores',
  'Redactores de carteles, pintores decorativos y grabadores',
  'Reguladores y operadores de máquinas de labrar madera',
  'Reguladores y operadores de máquinas herramientas',
  'Reparadores de bicicletas y afines',
  'Reponedores de estanterías',
  'Representantes comerciales',
  'Revisores y cobradores de los transportes públicos',
  'Revocadores',
  'Sastres, modistos, peleteros y sombrereros',
  'Secretarios (general)',
  'Secretarios administrativos y ejecutivos',
  'Secretarios jurídicos',
  'Secretarios médicos',
  'Sociólogos, antropólogos y afines',
  'Soldadores y oxicortadores',
  'Sopladores, modeladores, laminadores, cortadores y pulidores de vidrio',
  'Suboficiales de las fuerzas armadas',
  'Supervisores de industrias manufactureras',
  'Supervisores de la construcción',
  'Supervisores de mantenimiento y limpieza en oficinas, hoteles y otros establecimientos',
  'Supervisores de secretaría',
  'Supervisores de tiendas y almacenes',
  'Supervisores en ingeniería de minas',
  'Tapiceros, colchoneros y afines',
  'Tasadores',
  'Techadores',
  'Técnicos agropecuarios',
  'Técnicos de ingeniería de las telecomunicaciones',
  'Técnicos de la Web',
  'Técnicos de laboratorios médicos',
  'Técnicos de prótesis médicas y dentales',
  'Técnicos de radiodifusión y grabación audio visual',
  'Técnicos en aparatos de diagnóstico y tratamiento médico',
  'Técnicos en asistencia al usuario de tecnología de la información y las comunicaciones',
  'Técnicos en ciencias biológicas (excluyendo la medicina)',
  'Técnicos en ciencias físicas y en ingeniería no clasificados bajo otros epígrafes',
  'Técnicos en ciencias físicas y químicas',
  'Técnicos en control de procesos no clasificados bajo otros epígrafes',
  'Técnicos en documentación sanitaria',
  'Técnicos en electrónica',
  'Técnicos en galerías de arte, museos y bibliotecas',
  'Técnicos en ingeniería civil',
  'Técnicos en ingeniería de minas y metalurgia',
  'Técnicos en ingeniería mecánica',
  'Técnicos en operaciones de tecnología de la información y las comunicaciones',
  'Técnicos en optometría y ópticos',
  'Técnicos en química industrial',
  'Técnicos en redes y sistemas de computadores',
  'Técnicos en seguridad aeronáutica',
  'Técnicos forestales',
  'Técnicos y asistentes farmacéuticos',
  'Técnicos y asistentes fisioterapeutas',
  'Técnicos y asistentes veterinarios',
  'Telefonistas',
  'Tenedores de libros',
  'Trabajadores agrícolas de subsistencia',
  'Trabajadores agropecuarios de subsistencia',
  'Trabajadores ambulantes de servicios y afines',
  'Trabajadores comunitarios de la salud',
  'Trabajadores de explotaciones de acuicultura',
  'Trabajadores de los cuidados personales a domicilio',
  'Trabajadores de los cuidados personales en instituciones',
  'Trabajadores de los cuidados personales en servicios de salud no clasificados bajo otros epígrafes',
  'Trabajadores de servicios personales no clasificados bajo otros epígrafes',
  'Trabajadores forestales calificados y afines',
  'Trabajadores pecuarios de subsistencia',
  'Trabajadores y asistentes sociales de nivel medio',
  'Traductores, intérpretes y lingüistas',
  'Urbanistas e ingenieros de tránsito',
  'Vendedores ambulantes (excluyendo de comida)',
  'Vendedores ambulantes de productos comestibles',
  'Vendedores de comidas al mostrador',
  'Vendedores de quioscos y de puestos de mercado',
  'Vendedores no clasificados bajo otros epígrafes',
  'Vendedores por teléfono',
  'Vendedores puerta a puerta',
  'Veterinarios',
  'Zapateros y afines',
]
