/**
 * Listado oficial de Unidades Médicas del IGSS
 * Fuente: Listado de Unidades Médicas.xlsx (Hoja1)
 */
export const unidadesMedicas = [
  { nombre: "ANEXO DEL IGSS CONSULTORIO GUASTATOYA, EN SANARATE, EL PROGRESO", departamento: "EL PROGRESO" },
  { nombre: "CENTRO DE ATENCIÓN INTEGRAL DE SALUD MENTAL", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO DE ANTIGUA GUATEMALA, SACATEPÉQUEZ", departamento: "SACATEPÉQUEZ" },
  { nombre: "CONSULTORIO DE CHIQUIMULA", departamento: "CHIQUIMULA" },
  { nombre: "CONSULTORIO DE TECÚN UMÁN, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "CONSULTORIO DEL INSTITUTO EN EL MUNICIPIO DE VILLA NUEVA, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO GUAZACAPÁN, SANTA ROSA", departamento: "SANTA ROSA" },
  { nombre: "CONSULTORIO IGSS, JALAPA", departamento: "JALAPA" },
  { nombre: "CONSULTORIO IGSS, JUTIAPA", departamento: "JUTIAPA" },
  { nombre: "CONSULTORIO IGSS, SALAMÁ, BAJA VERAPAZ", departamento: "BAJA VERAPAZ" },
  { nombre: "CONSULTORIO LA GOMERA, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "CONSULTORIO LOS AMATES, IZABAL", departamento: "IZABAL" },
  { nombre: "CONSULTORIO MORALES, IZABAL", departamento: "IZABAL" },
  { nombre: "CONSULTORIO PUERTO DE SAN JOSÉ, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "CONSULTORIO SAN JOSÉ PINULA, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO SAN MARCOS, S.M.", departamento: "SAN MARCOS" },
  { nombre: "CONSULTORIO SANTA CRUZ DEL QUICHÉ, QUICHÉ", departamento: "QUICHÉ" },
  { nombre: "CONSULTORIO TOTONICAPÁN, TOTONICAPÁN", departamento: "TOTONICAPÁN" },
  { nombre: "CONSULTORIO Y SALA ANEXA DEL HOSPITAL NACIONAL DE SOLOLÁ", departamento: "SOLOLÁ" },
  { nombre: "CONSULTORIO ZACAPA, ZACAPA", departamento: "ZACAPA" },
  { nombre: "CAMIP - CENTRO DE ATENCIÓN MÉDICA INTEGRAL PARA PENSIONADOS", departamento: "GUATEMALA" },
  { nombre: "CAMIP 2 BARRANQUILLA", departamento: "GUATEMALA" },
  { nombre: "CAMIP 3 ZUNIL", departamento: "QUETZALTENANGO" },
  { nombre: "CENTRO DE ATENCIÓN MÉDICA SAYAXCHÉ", departamento: "PETÉN" },
  { nombre: "CLÍNICA DE PERSONAL", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO EL ESTOR, IZABAL", departamento: "IZABAL" },
  { nombre: "CONSULTORIO FINCA SANTA LEONARDA, VILLA CANALES", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO FRAIJANES, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO GUALÁN, ZACAPA", departamento: "ZACAPA" },
  { nombre: "CONSULTORIO GUASTATOYA, EL PROGRESO", departamento: "EL PROGRESO" },
  { nombre: "CONSULTORIO LA DEMOCRACIA, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "CONSULTORIO MASAGUA, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "CONSULTORIO PALENCIA, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO PUERTO CHAMPERICO, RETALHULEU", departamento: "RETALHULEU" },
  { nombre: "CONSULTORIO SAN FELIPE, RETALHULEU", departamento: "RETALHULEU" },
  { nombre: "CONSULTORIO SAN JUAN COTZAL, QUICHÉ", departamento: "QUICHÉ" },
  { nombre: "CONSULTORIO SAN LUCAS TOLIMÁN, SOLOLÁ", departamento: "SOLOLÁ" },
  { nombre: "CONSULTORIO SIQUINALÁ, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "CONSULTORIO VILLA CANALES, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO EN PALÍN, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "HOSPITAL GENERAL DOCTOR JUAN JOSÉ ARÉVALO BERMEJO", departamento: "GUATEMALA" },
  { nombre: "HOSPITAL DE REHABILITACIÓN", departamento: "GUATEMALA" },
  { nombre: "HOSPITAL GENERAL DE ENFERMEDADES", departamento: "GUATEMALA" },
  { nombre: "HOSPITAL DE GINECO-OBSTETRICIA", departamento: "GUATEMALA" },
  { nombre: "HOSPITAL GENERAL DE ACCIDENTES CEIBAL", departamento: "GUATEMALA" },
  { nombre: "HOSPITAL ESCUINTLA, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "HOSPITAL DE SANTA LUCÍA COTZUMALGUAPA, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "HOSPITAL DE TIQUISATE, ESCUINTLA", departamento: "ESCUINTLA" },
  { nombre: "HOSPITAL CHICACAO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "HOSPITAL DE MAZATENANGO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "HOSPITAL PATULUL, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "HOSPITAL CHIMALTENANGO, CHIMALTENANGO", departamento: "CHIMALTENANGO" },
  { nombre: "HOSPITAL DE ANTIGUA GUATEMALA, SACATEPÉQUEZ", departamento: "SACATEPÉQUEZ" },
  { nombre: "HOSPITAL RETALHULEU, RETALHULEU", departamento: "RETALHULEU" },
  { nombre: "HOSPITAL IGSS COATEPEQUE, QUETZALTENANGO", departamento: "QUETZALTENANGO" },
  { nombre: "HOSPITAL GENERAL DE QUETZALTENANGO", departamento: "QUETZALTENANGO" },
  { nombre: "HOSPITAL COLOMBA COSTA CUCA, QUETZALTENANGO", departamento: "QUETZALTENANGO" },
  { nombre: "HOSPITAL DE HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "HOSPITAL EL TUMBADOR, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "HOSPITAL MALACATÁN, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "HOSPITAL PUERTO BARRIOS, IZABAL", departamento: "IZABAL" },
  { nombre: "HOSPITAL IGSS COBÁN, ALTA VERAPAZ", departamento: "ALTA VERAPAZ" },
  { nombre: "HOSPITAL DE CUILAPA, SANTA ROSA", departamento: "SANTA ROSA" },
  { nombre: "HOSPITAL POCHUTA, CHIMALTENANGO", departamento: "CHIMALTENANGO" },
  { nombre: "POLICLÍNICA CENTRAL", departamento: "GUATEMALA" },
  { nombre: "UNIDAD ASISTENCIAL AMATITLÁN", departamento: "GUATEMALA" },
  { nombre: "UNIDAD ASISTENCIAL DE SAN JUAN SACATEPÉQUEZ", departamento: "GUATEMALA" },
  { nombre: "UNIDAD DE CONSULTA EXTERNA DE ENFERMEDADES - AUTONOMÍA", departamento: "GUATEMALA" },
  { nombre: "UNIDAD DE CONSULTA EXTERNA DE ESPECIALIDADES - GERONA/ONCOLOGÍA", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 5", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 11", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 12", departamento: "GUATEMALA" },
  // Unidades Integrales y Puestos de Salud (MSPAS registry)
  { nombre: "UNIDAD INTEGRAL DE LA DEMOCRACIA, HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "UNIDAD INTEGRAL DE SAN ANTONIO HUISTA, HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "UNIDAD INTEGRAL DE SAN ILDEFONSO IXTAHUACÁN, HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "UNIDAD INTEGRAL DE SAN PEDRO NECTÁ, HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "UNIDAD INTEGRAL DE SANTA CRUZ BARILLAS, HUEHUETENANGO", departamento: "HUEHUETENANGO" },
  { nombre: "UNIDAD INTEGRAL DE ASUNCIÓN MITA, JUTIAPA", departamento: "JUTIAPA" },
  { nombre: "CONSULTORIO LA LIBERTAD, PETÉN", departamento: "PETÉN" },
  { nombre: "CONSULTORIO POPTÚN, PETÉN", departamento: "PETÉN" },
  { nombre: "CONSULTORIO SAYAXCHÉ, PETÉN", departamento: "PETÉN" },
  { nombre: "SALA ANEXA HOSPITAL NACIONAL SAN BENITO, PETÉN", departamento: "PETÉN" },
  { nombre: "CONSULTORIO NEBAJ, QUICHÉ", departamento: "QUICHÉ" },
  { nombre: "UNIDAD INTEGRAL DE EL QUETZAL, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE IXCHIGUÁN, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE LA REFORMA, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE NUEVO PROGRESO, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE SAN PEDRO SACATEPÉQUEZ, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE SAN RAFAEL PIE DE LA CUESTA, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "UNIDAD INTEGRAL DE TEJUTLA, SAN MARCOS", departamento: "SAN MARCOS" },
  { nombre: "PUESTO DE SALUD PUEBLO NUEVO VIÑAS, SANTA ROSA", departamento: "SANTA ROSA" },
  { nombre: "UNIDAD INTEGRAL DE CUYOTENANGO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE RÍO BRAVO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE SAN ANTONIO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE SAN FRANCISCO ZAPOTITLÁN, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE SAN JOSÉ EL ÍDOLO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE SANTA BÁRBARA, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "UNIDAD INTEGRAL DE SANTO DOMINGO, SUCHITEPÉQUEZ", departamento: "SUCHITEPÉQUEZ" },
  { nombre: "PUESTO DE SALUD DE SAN PEDRO YEPOCAPA, CHIMALTENANGO", departamento: "CHIMALTENANGO" },
  { nombre: "PUESTO DE SALUD DE SAN FRANCISCO COTZAL, QUICHÉ", departamento: "QUICHÉ" },
  // Unidades legacy del portal IGSS (agregadas v2 - abril 2026)
  { nombre: "HOSPITAL IGSS JALAPA", departamento: "JALAPA" },
  { nombre: "CONSULTORIO ROOSEVELT, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO MIXCO, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO PETAPA, GUATEMALA", departamento: "GUATEMALA" },
  { nombre: "CONSULTORIO QUETZALTENANGO, QUETZALTENANGO", departamento: "QUETZALTENANGO" },
  { nombre: "CONSULTORIO COBÁN, ALTA VERAPAZ", departamento: "ALTA VERAPAZ" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 7", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 18", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA ZONA 21 (LAS ILUSIONES)", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA EL MILAGRO", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA CHINAUTLA", departamento: "GUATEMALA" },
  { nombre: "UNIDAD PERIFÉRICA SAN MIGUEL PETAPA", departamento: "GUATEMALA" },
  { nombre: "OTRA", departamento: "" },
]

// Obtener solo los nombres para el select
export const unidadesMedicasNombres = unidadesMedicas.map(u => u.nombre)
